import type { PrismaClient } from '../../prisma/generated/client/index.js';
import type { PromoMetricSnapshotPayload } from '../schemas/promoSchemas';
import { type PromoMetrics } from './promoRewardPolicyService';
export declare const recordPromoMetricsAndSettle: (db: PrismaClient, claimId: number, payload: PromoMetricSnapshotPayload, actorId: number) => Promise<{
    claim: {
        id: number;
        user_id: number;
        created_at: Date;
        updated_at: Date;
        platform_user_id: string;
        verified_at: Date | null;
        task_id: number;
        video_url: string | null;
        platform_video_id: string | null;
        platform_author_id: string | null;
        publish_at: Date | null;
        claim_status: string;
        reward_status: string;
        settlement_status: string;
        highest_rewarded_tier: string | null;
        total_rewarded_amount: number;
        last_metric_at: Date | null;
        verify_result: string | null;
        verify_detail: string | null;
        proof_data: string | null;
        claim_request_no: string;
        claim_no: number;
        idempotency_key: string;
        claim_at: Date;
        rewarding_at: Date | null;
        rewarded_at: Date | null;
        failed_reason: string | null;
        audit_by: number | null;
        audit_note: string | null;
    };
    snapshot: {
        id: number;
        created_at: Date;
        source: string;
        comments: number;
        likes: number;
        favorites: number;
        created_by: number | null;
        views: number;
        shares: number;
        coins: number;
        claim_id: number;
        source_ref: string | null;
        raw_summary: string | null;
        captured_at: Date;
    };
    settlement: null;
    evaluation: {
        metrics: PromoMetrics;
        qualifiedTier: {
            key: string;
            name: string;
            rewardAmount: number;
            minViews?: number | undefined;
            minLikes?: number | undefined;
            minComments?: number | undefined;
            minShares?: number | undefined;
            minFavorites?: number | undefined;
            minCoins?: number | undefined;
        } | null;
        qualifiedIndex: number;
        isHighestTier: boolean;
        nextTier: {
            key: string;
            name: string;
            rewardAmount: number;
            minViews?: number | undefined;
            minLikes?: number | undefined;
            minComments?: number | undefined;
            minShares?: number | undefined;
            minFavorites?: number | undefined;
            minCoins?: number | undefined;
        } | null;
    };
    paidAmount: number;
} | {
    claim: {
        id: number;
        user_id: number;
        created_at: Date;
        updated_at: Date;
        platform_user_id: string;
        verified_at: Date | null;
        task_id: number;
        video_url: string | null;
        platform_video_id: string | null;
        platform_author_id: string | null;
        publish_at: Date | null;
        claim_status: string;
        reward_status: string;
        settlement_status: string;
        highest_rewarded_tier: string | null;
        total_rewarded_amount: number;
        last_metric_at: Date | null;
        verify_result: string | null;
        verify_detail: string | null;
        proof_data: string | null;
        claim_request_no: string;
        claim_no: number;
        idempotency_key: string;
        claim_at: Date;
        rewarding_at: Date | null;
        rewarded_at: Date | null;
        failed_reason: string | null;
        audit_by: number | null;
        audit_note: string | null;
    };
    snapshot: {
        id: number;
        created_at: Date;
        source: string;
        comments: number;
        likes: number;
        favorites: number;
        created_by: number | null;
        views: number;
        shares: number;
        coins: number;
        claim_id: number;
        source_ref: string | null;
        raw_summary: string | null;
        captured_at: Date;
    };
    settlement: {
        status: string;
        id: number;
        created_at: Date;
        idempotency_key: string;
        created_by: number | null;
        claim_id: number;
        metrics_snapshot_id: number | null;
        tier_key: string;
        tier_name: string;
        target_amount: number;
        paid_amount: number;
        calculation_snapshot: string;
    };
    evaluation: {
        metrics: PromoMetrics;
        qualifiedTier: {
            key: string;
            name: string;
            rewardAmount: number;
            minViews?: number | undefined;
            minLikes?: number | undefined;
            minComments?: number | undefined;
            minShares?: number | undefined;
            minFavorites?: number | undefined;
            minCoins?: number | undefined;
        } | null;
        qualifiedIndex: number;
        isHighestTier: boolean;
        nextTier: {
            key: string;
            name: string;
            rewardAmount: number;
            minViews?: number | undefined;
            minLikes?: number | undefined;
            minComments?: number | undefined;
            minShares?: number | undefined;
            minFavorites?: number | undefined;
            minCoins?: number | undefined;
        } | null;
    };
    paidAmount: number;
}>;
//# sourceMappingURL=promoMetricSettlementService.d.ts.map