CREATE TABLE "FreeDomainSuffix" ("id" SERIAL NOT NULL, "suffix" TEXT NOT NULL, "provider" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "prefix_pattern" TEXT NOT NULL DEFAULT '^[a-z][a-z0-9-]{2,15}$', "ttl" INTEGER NOT NULL DEFAULT 300, "quota_per_user" INTEGER NOT NULL DEFAULT 1, "reserved_words" TEXT NOT NULL DEFAULT '[]', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "FreeDomainSuffix_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FreeDomainSuffix_suffix_key" ON "FreeDomainSuffix"("suffix");
CREATE INDEX "FreeDomainSuffix_enabled_idx" ON "FreeDomainSuffix"("enabled");
CREATE INDEX "FreeDomainSuffix_provider_idx" ON "FreeDomainSuffix"("provider");
CREATE TABLE "ServerDomain" ("id" SERIAL NOT NULL, "server_id" INTEGER, "user_id" INTEGER NOT NULL, "suffix_id" INTEGER NOT NULL, "prefix" TEXT NOT NULL, "domain" TEXT NOT NULL, "target" TEXT NOT NULL, "port" INTEGER NOT NULL DEFAULT 25565, "application_status" TEXT NOT NULL DEFAULT 'PENDING_REVIEW', "dns_status" TEXT NOT NULL DEFAULT 'NOT_REQUESTED', "reviewed_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "ServerDomain_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServerDomain_server_id_key" ON "ServerDomain"("server_id");
CREATE UNIQUE INDEX "ServerDomain_domain_key" ON "ServerDomain"("domain");
CREATE INDEX "ServerDomain_user_id_application_status_idx" ON "ServerDomain"("user_id", "application_status");
CREATE INDEX "ServerDomain_suffix_id_prefix_idx" ON "ServerDomain"("suffix_id", "prefix");
CREATE INDEX "ServerDomain_dns_status_idx" ON "ServerDomain"("dns_status");
CREATE TABLE "DnsRecord" ("id" SERIAL NOT NULL, "server_domain_id" INTEGER NOT NULL, "record_type" TEXT NOT NULL, "name" TEXT NOT NULL, "content" TEXT NOT NULL, "ttl" INTEGER NOT NULL, "provider_record_id" TEXT, "created_by_platform" BOOLEAN NOT NULL DEFAULT true, "status" TEXT NOT NULL DEFAULT 'PENDING', "last_error" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "DnsRecord_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "DnsRecord_server_domain_id_record_type_name_content_key" ON "DnsRecord"("server_domain_id", "record_type", "name", "content");
CREATE INDEX "DnsRecord_provider_record_id_idx" ON "DnsRecord"("provider_record_id");
CREATE INDEX "DnsRecord_status_idx" ON "DnsRecord"("status");
CREATE TABLE "DnsTask" ("id" SERIAL NOT NULL, "server_domain_id" INTEGER NOT NULL, "action" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "attempts" INTEGER NOT NULL DEFAULT 0, "next_attempt_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "locked_at" TIMESTAMP(3), "last_error" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, CONSTRAINT "DnsTask_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "DnsTask_server_domain_id_action_key" ON "DnsTask"("server_domain_id", "action");
CREATE INDEX "DnsTask_status_next_attempt_at_idx" ON "DnsTask"("status", "next_attempt_at");
ALTER TABLE "ServerDomain" ADD CONSTRAINT "ServerDomain_server_id_fkey" FOREIGN KEY ("server_id") REFERENCES "Server"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ServerDomain" ADD CONSTRAINT "ServerDomain_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ServerDomain" ADD CONSTRAINT "ServerDomain_suffix_id_fkey" FOREIGN KEY ("suffix_id") REFERENCES "FreeDomainSuffix"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DnsRecord" ADD CONSTRAINT "DnsRecord_server_domain_id_fkey" FOREIGN KEY ("server_domain_id") REFERENCES "ServerDomain"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DnsTask" ADD CONSTRAINT "DnsTask_server_domain_id_fkey" FOREIGN KEY ("server_domain_id") REFERENCES "ServerDomain"("id") ON DELETE CASCADE ON UPDATE CASCADE;
