CREATE USER IF NOT EXISTS 'qfadmin'@'localhost' IDENTIFIED BY 'QfDb_103_Admin_2026!';
GRANT ALL PRIVILEGES ON *.* TO 'qfadmin'@'localhost' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'qfadmin'@'127.0.0.1' IDENTIFIED BY 'QfDb_103_Admin_2026!';
GRANT ALL PRIVILEGES ON *.* TO 'qfadmin'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;