import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { useCallback } from 'react';

// --- i18n Definitions ---
export type Locale = 'zh' | 'en';

export const TRANSLATIONS = {
  zh: {
    // Nav
    'nav.home': '首页',
    'nav.servers': '找服',
    'nav.news': '新闻',
    'nav.resources': '资源',
    'nav.team': '团队',
    'nav.rules': '规则',
    'nav.login': '登录',
    'nav.register': '快速注册',
    'nav.dashboard': '个人中心',
    'nav.logout': '退出登录',
    // Admin sidebar
    'admin.title': '千服联灯',
    'admin.console': '管理控制台',
    'admin.status': '根管理员',
    'admin.index': '总览',
    'admin.users': '用户管理',
    'admin.review': '服务器审核',
    'admin.tickets': '工单管理',
    'admin.reports': '举报管理',
    'admin.audit': '审计日志',
    'admin.stats': '数据统计',
    'admin.moderation': '内容审核',
    'admin.network': '端口安全',
    'admin.mail': '邮件配置',
    'admin.logout': '退出登录',
    // Settings Panel
    'prefs.title': '个性化设置',
    'prefs.subtitle': '语言 & 配色方案',
    'prefs.language': '语言选择',
    'prefs.accent': '全局配色',
    'prefs.footer': '千服联灯设置中心',
    'footer.status.normal': '公开 API 正常',
    'footer.status.checking': '公开 API 检测中',
    'footer.status.degraded': '公开 API 降级',
    // Home Page
    'home.hero.title': '找 Minecraft 服务器',
    'home.hero.subtitle': '按版本和玩法浏览服务器。服主也可以提交资料，审核通过后公开展示。',
    'home.hero.explore': '浏览服务器',
    'home.hero.promote': '提交服务器资料',
    'home.feat.security.title': '账户与内容安全',
    'home.feat.security.desc': '登录会话、敏感操作和公开内容分别经过身份验证、权限检查与审核流程，异常情况会留下可追踪记录。',
    'home.feat.auction.title': '免费长期展示',
    'home.feat.auction.desc': '服务器审核通过后免费长期展示，玩家可以按版本和玩法找到合适的服务器。',
    'home.feat.support.title': '人工支持',
    'home.feat.support.desc': '通过工单系统提交技术问题、内容审核或账户支持请求，平台会按流程跟进处理。',
    // Auth Page
    'auth.login.title': '账号登录',
    'auth.login.subtitle': '使用用户名或邮箱登录，登录后即可管理服务器、个人资料和工单记录。',
    'auth.login.submit': '登录',
    'auth.register.title': '创建账号',
    'auth.register.subtitle': '注册千服联灯账号，完成邮箱验证后即可发布服务器和提交工单。',
    'auth.register.submit': '注册并发送验证码',
    'auth.form.username.label': '用户名或邮箱',
    'auth.form.username.placeholder': '用户名 / 邮箱地址',
    'auth.form.password.label': '登录密码',
    'auth.form.password.placeholder': '请输入您的访问密码',
    'auth.form.email.label': '邮箱地址',
    'auth.form.email.placeholder': 'example@mail.com',
    'auth.form.agree': '我已阅读并同意平台服务条款与隐私政策',
    'auth.form.agree_prefix': '我已阅读并同意',
    'auth.form.terms': '服务条款',
    'auth.form.privacy': '隐私政策',
    'auth.form.recovery': '需要找回凭据？',
    'auth.form.new_node': '新节点？',
    'auth.form.init_reg': '初始化注册',
    'auth.form.has_node': '已有节点？',
    'auth.form.init_login': '执行登录指令',
    'auth.form.code.label': '验证码',
    'auth.form.confirmPassword.label': '确认密码',
    'auth.status.guest': '访客访问模式',
    'auth.status.granted': '授权通过',
    'auth.status.granted_desc': '欢迎回来，{user}。账号会话已恢复。',
    // Auth Stories
    'auth.story.1.title': '红石信号会衰减',
    'auth.story.1.desc': '红石线最多传递 15 格。线路较长时，需要在合适的位置放置中继器。',
    'auth.story.2.title': '村民需要固定工位',
    'auth.story.2.desc': '建造交易大厅时，先限制村民移动范围，再逐一放置并确认工作站。',
    'auth.story.3.title': '下界距离是 1:8',
    'auth.story.3.desc': '下界移动 1 格相当于主世界移动 8 格，适合修建跨区域交通线路。',
    'auth.story.4.title': '服务器介绍要写清楚',
    'auth.story.4.desc': '建议注明版本、玩法、开放时间、连接方式和主要规则，方便玩家判断是否适合加入。',
    'auth.story.5.title': '在这里发布服务器',
    'auth.story.5.desc': '提交服务器资料并通过审核后，玩家可以在公开列表中找到它。',
    // Admin Dashboard
    'admin.dash.title': '全局态势感知',
    'admin.dash.subtitle': '查看平台关键指标、待处理事项和运行状态，集中处理审核、工单与系统设置。',
    'admin.dash.metrics.users': '已注册实体',
    'admin.dash.metrics.servers': '活跃集群',
    'admin.dash.metrics.review': '待处理协议',
    'admin.dash.metrics.tickets': '活动工单',
    'admin.dash.flux': '实时通量',
    'admin.dash.uptime': '在线评分',
    'admin.dash.telemetry': '实时遥测数据包',
    'admin.dash.inspect_logs': '审查所有审计日志',
    'admin.dash.security_snap': '安全快照',
    'admin.dash.firewall': '防火墙完整性',
    'admin.dash.encryption': '认证加密协议',
    'admin.dash.threat': '威胁等级',
    'admin.dash.run_scan': '执行系统扫描',
    'admin.dash.maintenance': '维护纪元',
    'admin.dash.sync_msg': '全球同步预计于 {time} 后开始',
    'admin.dash.sync_desc': '下次计划维护将同步所有节点并轮换加密会话密钥。',
    'dash.activity.title': '近期活动日志',
    'dash.activity.sync': '资料同步完成',
    'dash.activity.handshake': '账号安全验证通过',
    'dash.activity.firewall': '系统安全状态正常',

    // User Dashboard
    'dash.menu.overview': '控制台概览',
    'dash.menu.servers': '我的服务器',
    'dash.menu.tickets': '工单系统',
    'dash.menu.profile': '账号设置',
    'dash.logout': '退出登录',
    'dash.level_progress': '等级进度',
    'dash.services_shortcuts': '服务与快捷方式',
    'dash.xp.remaining': '距离下一级还需要 {xp} XP',
    'dash.checkin.claimed': '今日已签到',
    'dash.checkin.now': '立即签到',
    'dash.checkin.xp_reward': '获得 10 XP 经验奖励！',
    // Public Server List
    'discovery.title': '发现服务器',
    'discovery.status': '目前共有 {count} 个已公开的服务器可浏览。',
    'discovery.status_loading_desc': '正在检查公开目录状态并同步最新服务器数据。',
    'discovery.protocol': '公开列表已开放',
    'discovery.protocol_checking': '公开目录检测中',
    'discovery.protocol_degraded': '公开 API 未就绪',
    'discovery.search.placeholder': '搜索名称、版本、玩法或标签',
    'discovery.load_more': '加载更多节点数据',
    'discovery.buffer': '列表状态: 正常',
    'discovery.buffer_checking': '列表状态: 检查中',
    'discovery.buffer_degraded': '列表状态: 降级',
    'discovery.status_error': '公开目录暂时不可用，请稍后重试。',
    'discovery.loaded_count': '已加载 {count} 个服务器',
    'discovery.loaded_pending': '正在拉取服务器数据',
    'discovery.loaded_unavailable': '服务器数据暂不可用',
    'discovery.nodes_online': '在线人数',
    'discovery.status_live': '公开展示中',
    'discovery.status_loading': '公开索引检测中',
    'discovery.status_degraded': '公开索引异常',
    'discovery.cat.all': '全部',
    'discovery.cat.survival': '生存',
    'discovery.cat.creative': '创造',
    'discovery.cat.hardcore': '极限',
    'discovery.cat.minigames': '小游戏',
    'discovery.cat.roleplay': '角色扮演',
    'dash.shortcuts.publish': '发布服务器',
    'dash.shortcuts.ticket': '发起工单',
    // My Servers
    'dash.servers.title': '我的服务器',
    'dash.servers.broadcast': '发布新服务器',
    'dash.servers.status.approved': '已发布',
    'dash.servers.status.pending': '审核中',
    'dash.servers.status.rejected': '已驳回',
    // Server Editor
    'editor.title.new': '发布服务器',
    'editor.title.edit': '编辑服务器',
    'editor.subtitle': '填写服务器版本、玩法、地址和介绍。审核通过后会进入公开列表。',
    'editor.step.init': '创建新服务器',
    'editor.step.edit': '正在编辑：{id}',
    'editor.field.name.label': '服务器名称',
    'editor.field.name.placeholder': '例如：星辰原野',
    'editor.field.version.label': '客户端版本',
    'editor.field.version.placeholder': '例如：1.20.1',
    'editor.field.ip.label': '连接地址',
    'editor.field.ip.placeholder': '例如: mc.matrix.local',
    'editor.field.tags.label': '分类标签',
    'editor.field.tags.placeholder': '例如：生存 战争 纯净',
    'editor.field.desc.label': '详细介绍',
    'editor.field.desc.placeholder': '详细介绍您的服务器玩法、规则、社区特色...',
    'editor.hero.label': '宣传图封面',
    'editor.hero.hint': '建议比例 16:9，最大 5MB',
    'editor.hero.upload': '上传封面',
    'editor.hero.current': '当前封面',
    'editor.hero.change': '更换图片',
    'editor.notice.title': '审核流程须知',
    'editor.notice.desc': '提交后将进入人工审核流程，通常在 24 小时内完成。审核期间请确保服务器 IP 保持在线状态。',
    'editor.submit.new': '提交审核',
    'editor.submit.edit': '保存修改',
    // Rich Text Editor Toolbar
    'editor.toolbar.bold': '加粗',
    'editor.toolbar.italic': '斜体',
    'editor.toolbar.underline': '下划线',
    'editor.toolbar.strike': '删除线',
    'editor.toolbar.link': '链接',
    'editor.toolbar.image': '插入图片',
    'editor.toolbar.h1': '一级标题',
    'editor.toolbar.h2': '二级标题',
    'editor.toolbar.bullet': '无序列表',
    'editor.toolbar.ordered': '有序列表',
    'editor.toolbar.align.left': '左对齐',
    'editor.toolbar.align.center': '居中对齐',
    'editor.toolbar.align.right': '右对齐',
    'editor.toolbar.code': '代码块',
    'editor.toolbar.table': '插入表格',
    'editor.toolbar.color': '文字颜色',
    'editor.toolbar.clear': '清除格式',
    'editor.toolbar.stats.chars': '字符数',
    'editor.toolbar.stats.words': '字数',


    // Support Tickets
    'ticket.create.title': '提交工单',
    'ticket.create.subtitle': '请详细描述您遇到的问题，我们会竭诚为您解决。',
    'ticket.form.subject': '工单标题',
    'ticket.form.subject.placeholder': '简明扼要地描述您的问题',
    'ticket.form.type': '工单分类',
    'ticket.form.type.general': '一般咨询',
    'ticket.form.type.billing': '账户支持',
    'ticket.form.type.technical': '技术故障',
    'ticket.form.type.report': '违规举报',
    'ticket.form.content': '详细内容',
    'ticket.form.content.placeholder': '请输入您问题的详细细节、截图链接或其他补充信息...',
    'ticket.status.submitted': '提交成功',
    'ticket.status.submitted_desc': '技术支持团队将尽快回复您的工单',
    'ticket.footer.hint': '在提交前，请确保您已阅读过帮助文档。我们的平均回复时间为 4 小时。',
    'ticket.back': '返回工单列表',
    'ticket.list.title': '我的工单',
    'ticket.list.desc': '提交您在使用过程中遇到的任何问题',
    'ticket.list.create': '提交新工单',
    'ticket.list.updated': '最近更新时间',
    // Profile Identity
    'profile.edit.title': '账号资料',
    'profile.tags.title': '用户画像',
    'profile.edit.avatar.label': '头像',
    'profile.edit.avatar.hint': '建议尺寸 400x400，支持 PNG / JPG',
    'profile.edit.avatar.change': '更换头像',
    'profile.edit.basic.title': '基础资料',
    'profile.edit.basic.username': '用户名',
    'profile.edit.basic.email': '邮箱地址',
    'profile.edit.basic.display_name': '显示名称',
    'profile.edit.basic.bio': '个人简介',
    'profile.edit.security.title': '密码与安全',
    'profile.edit.security.current': '当前密码',
    'profile.edit.security.new': '新密码',
    'profile.edit.security.confirm': '确认新密码',
    'profile.edit.submit.basic': '保存资料',
    'profile.edit.submit.security': '更新密码',
    // Password Reset
    'auth.reset.title': '设置新密码',
    'auth.reset.subtitle': '请为您的账号设置一个强密码。',
    'auth.reset.new_pwd': '新密码',
    'auth.reset.confirm_pwd': '确认新密码',
    'auth.reset.submit': '重置密码',
    'auth.reset.success': '密码已重置',
    'auth.reset.success_desc': '您现在可以使用新密码登录',
    'auth.reset.invalid': '无效的请求',
    'auth.reset.missing_token': '缺少重置令牌',
    // Profile
    'profile.role.admin': '系统管理员',
    'profile.role.user': '标准节点',
    'profile.checkin': '每日握手',
    'profile.support.title': '技术支持',
    'profile.support.desc': '提交工单并查看处理进度。',
    'profile.activity.title': '最近动态',
    'profile.checkin.success': '签到成功，经验值已发放',
    // Email Verify
    'auth.verify.title': '验证您的邮箱',
    'auth.verify.desc': '请输入发送至您注册邮箱的 6 位验证码以解锁受限功能。',
    'auth.verify.submit': '立即验证并解锁',
    'auth.verify.resend': '重新发送验证码',
    'auth.verify.sending': '正在发送中...',
    'auth.verify.success': '验证成功',
    'auth.verify.success_desc': '所有受限功能已为您解锁!',
    'auth.verify.sent': '验证码已发送',
    'auth.verify.sent_desc': '请检查您的收件箱',
    // Home extras
    'home.stats.nodes': '在线节点',
    'home.stats.users': '注册用户',
    'home.stats.servers': '已收录服务器',
    'home.stats.players': '实时在线玩家',
    'home.stats.latency': '同步延迟',
    'home.stats.response': '响应时间',
    'home.stats.availability': '在线率',
    'home.status.connected': '已连接',
    'home.status.probing': '检测中',
    'home.status.degraded': '已降级',
    'home.status.sync': '数据可用',
    'home.status.sync_pending': '等待同步',
    'home.status.sync_issue': '同步异常',
    'home.status.banner_label': '公开 API 状态',
    'home.status.banner_desc': '当前公开接口不可用，首页正在以降级模式展示静态内容，实时节点与同步指标暂时无法刷新。',
    'home.protocol': '协议: Liandeng_v4.0_Core',
    'home.learn_more': '了解更多',
    // Public Profile
    'profile.public.joined': '加入于',
    'profile.public.likes': '获得获赞',
    'profile.public.servers': '发布的服务器',
    'profile.public.view_detail': '查看详情',
    'profile.public.mysterious': '这位用户很神秘，还没有写下自我介绍。',
    // Admin Statuses
    'admin.status.enforced': '强力执行',
    'admin.status.minimal': '极低威胁',
    'admin.status.operational': '系统运行正常',
    // Common
    'common.loading': '加载中...',
    'common.success': '操作成功',
    'common.error': '操作失败',
    'common.retry': '重试',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.submit': '提交',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.settings': '设置',
    'common.page': '页码',
    'common.language': '语言',
    'common.accent': '配色',
    'common.sys_hint': '系统提示',
    'common.net_timeout': '网络超时',
    'common.net_timeout_desc': '请求处理时间过长，请稍后重试',
    // Server
    'server.join': '加入服务器',
    'server.online': '在线',
    'server.offline': '离线',
    // Auth
    'auth.email': '邮箱地址',
    'auth.password': '密码',
    'auth.username': '用户名',
    // Auth - Forgot Password
    'auth.forgot.title': '忘记密码？',
    'auth.forgot.subtitle': '请输入您的邮箱地址，我们将发送验证码以重置您的密码。',
    'auth.forgot.send_code': '发送验证码',
    'auth.forgot.verify_hint': '验证码已发送至 {email}',
    'auth.forgot.resend': '重新发送',
    'auth.forgot.verify': '验证',
    'auth.forgot.reset': '重置密码',
    'auth.no_account': '还没有账号？',
    'auth.has_account': '已有账号？',
    // Server Detail (Hub)
    'detail.nav.back': '返回服务器列表',
    'detail.nav.ref': '服务器编号',
    'detail.status.active': '服务器运行中',
    'detail.protocol.v': '通讯协议 v',
    'detail.side.endpoint': '网络端点',
    'detail.side.ip_label': '服务器 IP 地址',
    'detail.side.nodes_active': '当前在线人数',
    'detail.side.affinity': '社区热度',
    'detail.side.intel': '服务器资料',
    'detail.side.handshake': '握手完整性',
    'detail.side.optimal': '最佳',
    'detail.tabs.overview': '总览',
    'detail.tabs.community': '社区动态',
    'detail.tabs.technical': '技术规格',
    'detail.tabs.rules': '规则说明',
    'detail.tabs.online': '在线',
    'detail.overview.mission': '节点任务简报',
    'detail.overview.init_content': '正在初始化内容流...',
    'detail.overview.feat_primary': '核心特性',
    'detail.overview.feat_latency': '低延迟连接',
    'detail.overview.feat_dist': '稳定运行',
    'detail.comm.auth_user': '已授权用户',
    'detail.comm.session_stable': '会话稳定',
    'detail.comm.placeholder': '为社区动态流贡献内容...',
    'detail.comm.broadcast': '发布评论',
    'detail.comm.handshake_req': '需要建立握手',
    'detail.comm.auth_req_desc': '在贡献内容前，授权节点必须先完成同步。',
    'detail.comm.init_sync': '初始化身份同步',
    'detail.comm.live_feed': '实时动态流',
    'detail.comm.sort_latest': '排序: 最新优先',
    'detail.comm.verified': '认证节点',
    'detail.comm.authority': '官方认证',
    'detail.comm.supporter': '支持者',
    'detail.comm.reply': '回复动态',
    'detail.comm.report': '举报节点',
    'detail.tech.latency': '延迟优化',
    'detail.tech.uptime': '在线时长',
    'detail.tech.integrity': '矩阵完整性',
    'detail.tech.excellent': '极佳',
    'detail.tech.stable': '稳定',
    'detail.tech.secure': '安全',
    'detail.tech.log_buffer': '技术日志缓冲区',
    'detail.side.top_nodes': '顶级实体',
    'detail.side.leaderboard': '查看完整排行榜',
    'detail.side.alert': '安全警报',
    'detail.side.integrity_guaranteed': '节点完整性受保障',
    'detail.side.encrypted': '账户请求通过 HTTPS 传输，并在服务端执行身份与权限校验。',
    'detail.side.sys_ver': '系统版本',
    'detail.side.ready': '就绪',
    // Server Portal
    'portal.handshake.init': '握手初始化...',
    'portal.protocol.secure': '协议: 安全深层链接 v4.2',
    'portal.authenticating': '正在认证数据负载',
    'portal.status.granted': '授权通过',
    'portal.status.secure': '安全连接',
    'portal.field.endpoint': '端点 IP',
    'portal.field.version': '版本',
    'portal.action.join': '初始化加入',
    'portal.diag.stream': '诊断流',
    'portal.diag.mapped': '您的身份矩阵已成功映射至节点集群',
    'portal.diag.latency': '延迟优化',
    'portal.diag.load': '集群负载',
    'portal.diag.security': '安全层级',
    'portal.diag.uptime': '节点在线率',
    'portal.diag.tunnel': '隧道稳定',
    'portal.diag.terminate': '终止连接',
    'portal.status.denied': '访问拒绝。',
    'portal.status.invalid_token': '所提供的授权令牌无效或已过期。',
    'portal.action.return': '返回探索门户',
    'portal.footer.ver': '安全门户 v4.0',
  },
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.servers': 'Servers',
    'nav.news': 'News',
    'nav.resources': 'Resources',
    'nav.team': 'Team',
    'nav.rules': 'Rules',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    // Admin sidebar
    'admin.title': 'QianFu',
    'admin.console': 'Admin Console',
    'admin.status': 'Root_Admin',
    'admin.index': 'Index',
    'admin.users': 'Directory',
    'admin.review': 'Review',
    'admin.tickets': 'Support',
    'admin.reports': 'Sanctions',
    'admin.audit': 'Ledger',
    'admin.stats': 'Insight',
    'admin.moderation': 'Guard',
    'admin.network': 'Network',
    'admin.mail': 'Mail',
    'admin.logout': 'Terminate Session',
    // Settings Panel
    'prefs.title': 'Preferences',
    'prefs.subtitle': 'Language & Accent Palette',
    'prefs.language': 'Select Language',
    'prefs.accent': 'Global Accent',
    'prefs.footer': 'QianFu Settings Center',
    'footer.status.normal': 'Public API normal',
    'footer.status.checking': 'Public API checking',
    'footer.status.degraded': 'Public API degraded',
    // Home Page
    'home.hero.title': 'Find a Minecraft Server',
    'home.hero.subtitle': 'Browse by version and game mode. Server owners can submit a listing for review.',
    'home.hero.explore': 'Browse Servers',
    'home.hero.promote': 'Submit Server Details',
    'home.feat.security.title': 'Account and Content Safety',
    'home.feat.security.desc': 'Sign-in sessions, sensitive actions, and public content pass through authentication, authorization, and review with traceable records.',
    'home.feat.auction.title': 'Free Long-Term Listings',
    'home.feat.auction.desc': 'Approved servers remain listed for free so players can find them by version and game mode.',
    'home.feat.support.title': 'Human Support',
    'home.feat.support.desc': 'Use the ticket desk for technical issues, review appeals, and account support.',
    // Auth Page
    'auth.login.title': 'Sign In',
    'auth.login.subtitle': 'Sign in with your username or email to manage listings, billing, and support tickets.',
    'auth.login.submit': 'Sign In',
    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Create your QianFu account, verify your email, and start publishing or promoting your server.',
    'auth.register.submit': 'Register & Send Code',
    'auth.form.username.label': 'Username or Email',
    'auth.form.username.placeholder': 'Username / Email',
    'auth.form.password.label': 'Password',
    'auth.form.password.placeholder': 'Enter access passphrase',
    'auth.form.email.label': 'Email Address',
    'auth.form.email.placeholder': 'example@mail.com',
    'auth.form.agree': 'I agree to the Terms of Service and Privacy Policy',
    'auth.form.agree_prefix': 'I have read and agree to the',
    'auth.form.terms': 'Terms of Service',
    'auth.form.privacy': 'Privacy Policy',
    'auth.form.recovery': 'Recovery Needed?',
    'auth.form.new_node': 'New Node?',
    'auth.form.init_reg': 'Initialize Register',
    'auth.form.has_node': 'Already have node?',
    'auth.form.init_login': 'Execute Login',
    'auth.status.guest': 'Guest Access Mode',
    'auth.status.granted': 'ACCESS GRANTED',
    'auth.status.granted_desc': 'Welcome back, {user}. Your session has been restored.',
    // Auth Stories
    'auth.story.1.title': 'Redstone signals have a range.',
    'auth.story.1.desc': 'Redstone dust carries a signal for 15 blocks. Add repeaters where longer runs need them.',
    'auth.story.2.title': 'Villagers need assigned workstations.',
    'auth.story.2.desc': 'For a trading hall, restrict movement first, then place and verify each workstation.',
    'auth.story.3.title': 'Nether travel uses a 1:8 ratio.',
    'auth.story.3.desc': 'One block in the Nether equals eight blocks in the Overworld, which makes long-distance routes practical.',
    'auth.story.4.title': 'Write a useful server description.',
    'auth.story.4.desc': 'List the version, game mode, opening hours, connection details, and main rules.',
    'auth.story.5.title': 'Publish your server here.',
    'auth.story.5.desc': 'Submit accurate server details. Approved listings appear in the public directory.',
    // Admin Dashboard
    'admin.dash.title': 'OmniView',
    'admin.dash.subtitle': 'Monitor global data and real-time operations. Execute scans, predict loads, and analyze interaction links.',
    'admin.dash.metrics.users': 'Registered Entities',
    'admin.dash.metrics.servers': 'Active Clusters',
    'admin.dash.metrics.review': 'Pending Protocols',
    'admin.dash.metrics.tickets': 'Active Tickets',
    'admin.dash.flux': 'Real-time Flux',
    'admin.dash.uptime': 'Uptime Score',
    'admin.dash.telemetry': 'Live Telemetry Packets',
    'admin.dash.inspect_logs': 'INSPECT ALL AUDIT LOGS',
    'admin.dash.security_snap': 'Security Snapshot',
    'admin.dash.firewall': 'Firewall Integrity',
    'admin.dash.encryption': 'Auth Encryption',
    'admin.dash.threat': 'Threat Level',
    'admin.dash.run_scan': 'RUN_SYSTEM_SCAN',
    'admin.dash.maintenance': 'Maintenance Epoch',
    'admin.dash.sync_msg': 'Global Sync in {time}',
    'admin.dash.sync_desc': 'Next scheduled maintenance will synchronize all nodes and rotate cryptographic session keys.',
    'dash.activity.title': 'Recent Activity',
    'dash.activity.sync': 'Profile synchronization completed',
    'dash.activity.handshake': 'Secure Handshake established with Node #001',
    'dash.activity.firewall': 'Firewall status: ALL_NODES_SECURE',

    // User Dashboard
    'dash.menu.overview': 'Overview',
    'dash.menu.servers': 'My Servers',
    'dash.menu.tickets': 'Tickets',
    'dash.menu.profile': 'Profile',
    'dash.logout': 'Logout',
    'dash.level_progress': 'Level Progress',
    'dash.services_shortcuts': 'Services & Shortcuts',
    'dash.xp.remaining': 'Need {xp} XP for next level',
    'dash.checkin.claimed': 'Already Claimed',
    'dash.checkin.now': 'Check-in Now',
    'dash.checkin.xp_reward': 'Received 10 XP Reward!',
    // Public Server List
    'discovery.title': 'Discovery.',
    'discovery.status': 'There are currently {count} public servers available to browse.',
    'discovery.status_loading_desc': 'Checking the public directory and syncing the latest server data.',
    'discovery.protocol': 'Public directory online',
    'discovery.protocol_checking': 'Checking public directory',
    'discovery.protocol_degraded': 'Public API unavailable',
    'discovery.search.placeholder': 'Search by name, version, tag, or gameplay',
    'discovery.load_more': 'Load More',
    'discovery.buffer': 'List status: healthy',
    'discovery.buffer_checking': 'List status: checking',
    'discovery.buffer_degraded': 'List status: degraded',
    'discovery.status_error': 'The public directory is temporarily unavailable. Please try again later.',
    'discovery.loaded_count': '{count} servers loaded',
    'discovery.loaded_pending': 'Fetching server data',
    'discovery.loaded_unavailable': 'Server data unavailable',
    'discovery.nodes_online': 'Online Players',
    'discovery.status_live': 'Public Listing',
    'discovery.status_loading': 'Directory checking',
    'discovery.status_degraded': 'Directory degraded',
    'discovery.cat.all': 'All Servers',
    'discovery.cat.survival': 'Survival',
    'discovery.cat.creative': 'Creative',
    'discovery.cat.hardcore': 'Hardcore',
    'discovery.cat.minigames': 'Mini-Games',
    'discovery.cat.roleplay': 'Roleplay',
    'dash.shortcuts.publish': 'Publish Server',
    'dash.shortcuts.ticket': 'Open Ticket',
    // My Servers
    'dash.servers.title': 'My Servers',
    'dash.servers.broadcast': 'Create Listing',
    'dash.servers.status.approved': 'Published',
    'dash.servers.status.pending': 'Under Review',
    'dash.servers.status.rejected': 'Rejected',
    // Server Editor
    'editor.title.new': 'Publish Server',
    'editor.title.edit': 'Edit Server',
    'editor.subtitle': 'Showcase your unique world. Once submitted, your server will be presented to thousands of active players.',
    'editor.step.init': 'Create a New Listing',
    'editor.step.edit': 'Editing: {id}',
    'editor.field.name.label': 'Name',
    'editor.field.name.placeholder': 'Example: Star Harbor',
    'editor.field.version.label': 'Client Version',
    'editor.field.version.placeholder': 'Example: 1.20.1 / Core_v1.0',
    'editor.field.ip.label': 'Connection IP',
    'editor.field.ip.placeholder': 'Example: mc.matrix.local',
    'editor.field.tags.label': 'Categorical Tags',
    'editor.field.tags.placeholder': 'Example: Survival Combat Vanilla',
    'editor.field.desc.label': 'Details',
    'editor.field.desc.placeholder': 'Describe your gameplay, rules, community features...',
    'editor.hero.label': 'Cover Image',
    'editor.hero.hint': 'Recommended ratio: 16:9, max 5MB',
    'editor.hero.upload': 'Upload Cover',
    'editor.hero.current': 'Current Cover',
    'editor.hero.change': 'Replace Image',
    'editor.notice.title': 'Review Notice',
    'editor.notice.desc': 'Submission will enter manual review, typically completed within 24h. Please ensure server IP remains online.',
    'editor.submit.new': 'Submit for Review',
    'editor.submit.edit': 'Save Changes',
    // Rich Text Editor Toolbar
    'editor.toolbar.bold': 'Bold',
    'editor.toolbar.italic': 'Italic',
    'editor.toolbar.underline': 'Underline',
    'editor.toolbar.strike': 'Strikethrough',
    'editor.toolbar.link': 'Link',
    'editor.toolbar.image': 'Insert Image',
    'editor.toolbar.h1': 'Heading 1',
    'editor.toolbar.h2': 'Heading 2',
    'editor.toolbar.bullet': 'Bullet List',
    'editor.toolbar.ordered': 'Ordered List',
    'editor.toolbar.align.left': 'Align Left',
    'editor.toolbar.align.center': 'Align Center',
    'editor.toolbar.align.right': 'Align Right',
    'editor.toolbar.code': 'Code Block',
    'editor.toolbar.table': 'Insert Table',
    'editor.toolbar.color': 'Text Color',
    'editor.toolbar.clear': 'Clear Format',
    'editor.toolbar.stats.chars': 'Characters',
    'editor.toolbar.stats.words': 'Words',


    // Support Tickets
    'ticket.create.title': 'Create Ticket',
    'ticket.create.subtitle': 'Please describe your issue in detail, and we will do our best to help you.',
    'ticket.form.subject': 'Subject',
    'ticket.form.subject.placeholder': 'Briefly describe your issue',
    'ticket.form.type': 'Category',
    'ticket.form.type.general': 'General',
    'ticket.form.type.billing': 'Account support',
    'ticket.form.type.technical': 'Technical',
    'ticket.form.type.report': 'Report',
    'ticket.form.content': 'Details',
    'ticket.form.content.placeholder': 'Please enter the details of your issue, screenshot links, or other info...',
    'ticket.status.submitted': 'Submitted Successfully',
    'ticket.status.submitted_desc': 'Our support team will respond to your ticket as soon as possible.',
    'ticket.footer.hint': 'Please ensure you have read the documentation before submitting. Average response time is 4 hours.',
    'ticket.back': 'Back to Tickets',
    'ticket.list.title': 'My Tickets',
    'ticket.list.desc': 'Submit any issues you encounter during use.',
    'ticket.list.create': 'Submit New Ticket',
    'ticket.list.updated': 'Last Updated',
    // Profile Identity
    'profile.edit.title': 'Identity_Parameter_Sync',
    'profile.tags.title': 'User Profile Tags',
    'profile.edit.avatar.label': 'Identity_Manifest_Icon',
    'profile.edit.avatar.hint': 'Neural_Link Recommended: 400x400 (PNG/JPG)',
    'profile.edit.avatar.change': 'Recalibrate Icon',
    'profile.edit.basic.title': 'CORE_IDENTIFIERS',
    'profile.edit.basic.username': 'Identity_Handle',
    'profile.edit.basic.email': 'Data_Relay_Node',
    'profile.edit.basic.display_name': 'Display_Designation',
    'profile.edit.basic.bio': 'Personal_Manifest',
    'profile.edit.security.title': 'SECURITY_CIPHERS',
    'profile.edit.security.current': 'Current_Access_Key',
    'profile.edit.security.new': 'New_Cipher_Generation',
    'profile.edit.security.confirm': 'Validate_New_Cipher',
    'profile.edit.submit.basic': 'Synchronize_Identity',
    'profile.edit.submit.security': 'Update_Security_Ciphers',

    // Password Reset
    'auth.reset.title': 'Set New Password',
    'auth.reset.subtitle': 'Please set a strong password for your account.',
    'auth.reset.new_pwd': 'New Password',
    'auth.reset.confirm_pwd': 'Confirm New Password',
    'auth.reset.submit': 'Reset Password',
    'auth.reset.success': 'Password Reset Successfully',
    'auth.reset.success_desc': 'You can now login with your new password.',
    'auth.reset.invalid': 'Invalid Request',
    'auth.reset.missing_token': 'Missing reset token',
    // Profile
    'profile.role.admin': 'System Administrator',
    'profile.role.user': 'Standard Node',
    'profile.checkin': 'Daily Handshake',
    'profile.support.title': 'Technical Support',
    'profile.support.desc': 'Access the encrypted support grid for node assistance.',
    'profile.activity.title': 'Temporal Telemetry',
    'profile.checkin.success': 'Handshake successful, Credits sent',
    // Email Verify
    'auth.verify.title': 'Verify Your Email',
    'auth.verify.desc': 'Please enter the 6-digit code sent to your registered email to unlock restricted features.',
    'auth.verify.submit': 'Verify & Unlock Now',
    'auth.verify.resend': 'Resend Verification Code',
    'auth.verify.sending': 'Sending...',
    'auth.verify.success': 'Verification Successful',
    'auth.verify.success_desc': 'All restricted features have been unlocked!',
    'auth.verify.sent': 'Code Sent',
    'auth.verify.sent_desc': 'Please check your inbox.',
    // Home extras
    'home.stats.nodes': 'Online servers',
    'home.stats.users': 'Registered users',
    'home.stats.servers': 'Listed servers',
    'home.stats.players': 'Players online',
    'home.stats.latency': 'Last probe',
    'home.stats.response': 'API response',
    'home.stats.availability': 'Online rate',
    'home.status.connected': 'Connected',
    'home.status.probing': 'Checking',
    'home.status.degraded': 'Degraded',
    'home.status.sync': 'Data available',
    'home.status.sync_pending': 'Sync pending',
    'home.status.sync_issue': 'Sync issue',
    'home.status.banner_label': 'Public API status',
    'home.status.banner_desc': 'The public API is currently unavailable. The homepage is showing static content in degraded mode and live metrics cannot be refreshed right now.',
    'home.protocol': 'Protocol: Liandeng_v4.0_Core',
    'home.learn_more': 'Learn More',
    // Public Profile
    'profile.public.joined': 'Joined on',
    'profile.public.likes': 'Likes Received',
    'profile.public.servers': 'Published Servers',
    'profile.public.view_detail': 'View Detail',
    'profile.public.mysterious': 'This user is mysterious and has not written a bio yet.',
    // Admin Statuses
    'admin.status.enforced': 'ENFORCED',
    'admin.status.minimal': 'MINIMAL',
    'admin.status.operational': 'Systems: OPERATIONAL',
    // Common
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.settings': 'Settings',
    'common.page': 'PAGE',
    'common.language': 'Language',
    'common.accent': 'Accent Color',
    'common.sys_hint': 'System Alert',
    'common.net_timeout': 'Network Timeout',
    'common.net_timeout_desc': 'The request took too long. Please try again later.',
    // Server
    'server.join': 'Join Server',
    'server.online': 'Online',
    'server.offline': 'Offline',
    // Auth
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.username': 'Username',
    // Auth - Forgot Password
    'auth.forgot.title': 'Forgot Password?',
    'auth.forgot.subtitle': 'Enter your email address and we will send a verification code to reset your password.',
    'auth.forgot.send_code': 'Send Code',
    'auth.forgot.verify_hint': 'Code sent to {email}',
    'auth.forgot.resend': 'Resend',
    'auth.forgot.verify': 'Verify',
    'auth.forgot.reset': 'Reset Password',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    // Server Detail (Hub)
    'detail.nav.back': 'Back to Server List',
    'detail.nav.ref': 'Server ID',
    'detail.status.active': 'Server Running',
    'detail.protocol.v': 'Version ',
    'detail.side.endpoint': 'Connection',
    'detail.side.ip_label': 'Server Address',
    'detail.side.nodes_active': 'Players Online',
    'detail.side.affinity': 'Community Heat',
    'detail.side.intel': 'Server Profile',
    'detail.side.handshake': 'Connection Status',
    'detail.side.optimal': 'Healthy',
    'detail.tabs.overview': 'Overview',
    'detail.tabs.community': 'Community',
    'detail.tabs.technical': 'Technical',
    'detail.tabs.rules': 'Rules',
    'detail.tabs.online': 'ONLINE',
    'detail.overview.mission': 'Server Summary',
    'detail.overview.init_content': 'Loading content...',
    'detail.overview.feat_primary': 'Core Feature',
    'detail.overview.feat_latency': 'Low Latency',
    'detail.overview.feat_dist': 'Stable Runtime',
    'detail.comm.auth_user': 'Verified User',
    'detail.comm.session_stable': 'Session Ready',
    'detail.comm.placeholder': 'Share your experience with this server...',
    'detail.comm.broadcast': 'Post Comment',
    'detail.comm.handshake_req': 'Handshake Required',
    'detail.comm.auth_req_desc': 'Authorization node must be synchronized before contribution.',
    'detail.comm.init_sync': 'Sign In to Comment',
    'detail.comm.live_feed': 'Recent Comments',
    'detail.comm.sort_latest': 'Sort: Latest First',
    'detail.comm.verified': 'Verified',
    'detail.comm.authority': 'Official Team',
    'detail.comm.supporter': 'Supporter',
    'detail.comm.reply': 'Reply',
    'detail.comm.report': 'Report',
    'detail.tech.latency': 'Latency',
    'detail.tech.uptime': 'Uptime',
    'detail.tech.integrity': 'Review Status',
    'detail.tech.excellent': 'EXCELLENT',
    'detail.tech.stable': 'STABLE',
    'detail.tech.secure': 'SECURE',
    'detail.tech.log_buffer': 'Technical Notes',
    'detail.side.top_nodes': 'Top Creators',
    'detail.side.leaderboard': 'View Full Ranking',
    'detail.side.alert': 'Security Notice',
    'detail.side.integrity_guaranteed': 'Node Integrity Guaranteed',
    'detail.side.encrypted': 'Account requests use HTTPS transport and server-side identity and permission checks.',
    'detail.side.sys_ver': 'SYSTEM',
    'detail.side.ready': 'READY',
    // Server Portal
    'portal.handshake.init': 'Handshake_Init...',
    'portal.protocol.secure': 'Protocol: Secure_Deep_Link_v4.2',
    'portal.authenticating': 'Authenticating_Payload',
    'portal.status.granted': 'ACCESS_GRANTED',
    'portal.status.secure': 'Secure Connection',
    'portal.field.endpoint': 'ENDPOINT_IP',
    'portal.field.version': 'VERSION',
    'portal.action.join': 'Initialize Join',
    'portal.diag.stream': 'Diagnostic_Stream',
    'portal.diag.mapped': 'Your identity matrix has been successfully mapped to Node Cluster',
    'portal.diag.latency': 'Latency_Optimized',
    'portal.diag.load': 'Cluster_Load',
    'portal.diag.security': 'Security_Layer',
    'portal.diag.uptime': 'Uptime',
    'portal.diag.tunnel': 'Tunnel_Stable',
    'portal.diag.terminate': 'Terminate Connection',
    'portal.status.denied': 'Access_Denied.',
    'portal.status.invalid_token': 'The provided authorization token is invalid or has expired.',
    'portal.action.return': 'Return to Discovery',
    'portal.footer.ver': 'Secure_Portal_v4.0',
  },
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.zh;
export const DEFAULT_TRANSLATIONS = TRANSLATIONS.zh;

// --- Appearance Themes ---
export type AccentTheme = 'zinc' | 'amber' | 'emerald' | 'sky' | 'violet' | 'rose';

export const accentThemes: Record<AccentTheme, {
  name: string;
  nameZh: string;
  primary: string;
  dataAttr: string;
}> = {
  zinc:    { name: 'Obsidian', nameZh: '黑曜石', primary: '#18181b', dataAttr: 'zinc'    },
  amber:   { name: 'Lantern',  nameZh: '灯笼橙', primary: '#d97706', dataAttr: 'amber'   },
  emerald: { name: 'Forest',   nameZh: '森林绿', primary: '#059669', dataAttr: 'emerald' },
  sky:     { name: 'Diamond',  nameZh: '钻石蓝', primary: '#0284c7', dataAttr: 'sky'     },
  violet:  { name: 'Chorus',   nameZh: '紫颂花', primary: '#7c3aed', dataAttr: 'violet'  },
  rose:    { name: 'Nether',   nameZh: '地狱红', primary: '#e11d48', dataAttr: 'rose'    },
};

/** 
 * applyAccent - Injects theme attribute into the document root
 */
export function applyAccent(accent: AccentTheme) {
  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute('data-accent', accent);
  }
}

// --- Store Implementation ---
interface UIState {
  locale: Locale;
  accent: AccentTheme;
  setLocale: (locale: Locale) => void;
  setAccent: (accent: AccentTheme) => void;
}

export const useUIStore = create<UIState>()(
  persist(
    (set) => ({
      locale: 'zh',
      accent: 'zinc',
      setLocale: (locale) => set({ locale }),
      setAccent: (accent) => {
        set({ accent });
        applyAccent(accent);
      },
    }),
    { name: 'qianfu-ui-prefs' }
  )
);

/**
 * useT - Simple translation hook
 */
export function useT() {
  const currentLocale = useUIStore((s) => s.locale);
  
  return useCallback(
    (key: TranslationKey): string => {
      return TRANSLATIONS[currentLocale][key] || key;
    },
    [currentLocale]
  );
}

/**
 * staticT - Translation helper for non-React contexts
 */
export function staticT(key: TranslationKey): string {
  const state = useUIStore.getState();
  const locale = state.locale || 'zh';
  return TRANSLATIONS[locale][key] || key;
}
