import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { useCallback } from 'react';

// --- i18n Definitions ---
export type Locale = 'zh' | 'en';

export const TRANSLATIONS = {
  zh: {
    // Nav
    'nav.home': '首页',
    'nav.servers': '找服',
    'nav.resources': '资源',
    'nav.team': '团队',
    'nav.rules': '规则',
    'nav.promotion': '推广',
    'nav.login': '登录',
    'nav.register': '快速注册',
    'nav.dashboard': '个人中心',
    'nav.logout': '退出登录',
    // Admin sidebar
    'admin.title': '千服联灯',
    'admin.console': '管理控制台',
    'admin.status': '根管理员',
    'admin.index': '总览',
    'admin.users': '用户管理',
    'admin.review': '服务器审核',
    'admin.tickets': '工单管理',
    'admin.reports': '举报管理',
    'admin.audit': '审计日志',
    'admin.stats': '数据统计',
    'admin.moderation': '内容审核',
    'admin.network': '端口安全',
    'admin.treasury': '支付配置',
    'admin.logout': '退出登录',
    // Settings Panel
    'prefs.title': '个性化设置',
    'prefs.subtitle': '语言 & 配色方案',
    'prefs.language': '语言选择',
    'prefs.accent': '全局配色',
    'prefs.footer': '千服控制矩阵 v2.0',
    // Home Page
    'home.hero.title': '发现下一个世界',
    'home.hero.subtitle': '千服联灯是全网领先的 Minecraft 服务器推广与发现平台。基于公平竞价协议，让优质内容在数字矩阵中脱颖而出。',
    'home.hero.explore': '探索节点',
    'home.hero.promote': '初始化推广',
    'home.feat.security.title': '不可篡改的安全',
    'home.feat.security.desc': '基于 SuperTokens 深度认证，保护您的账户与交易安全。所有会话均通过加密令牌进行端到端校验。',
    'home.feat.auction.title': '动态竞价协议',
    'home.feat.auction.desc': '摒弃固定展位，采用实时竞价算法，流量分配更透明。每一次展示都经过全网节点的实时共识校验。',
    'home.feat.support.title': '行政级支持',
    'home.feat.support.desc': '7x24 小时工单系统，专业团队为您排忧解难。我们的响应延迟低至毫秒级，确保您的操作永不中断。',
    // Auth Page
    'auth.login.title': '身份识别',
    'auth.login.subtitle': '请输入您的访问凭据以同步全球矩阵数据。执行安全握手协议。',
    'auth.login.submit': '执行授权指令',
    'auth.register.title': '初始化节点',
    'auth.register.subtitle': '欢迎加入全球最大 Minecraft 联播矩阵。请填写下方表单以完成身份初始化。',
    'auth.register.submit': '同步注册协议',
    'auth.form.username.label': '身份标识',
    'auth.form.username.placeholder': '用户名 / 邮箱地址',
    'auth.form.password.label': '安全矩阵密钥',
    'auth.form.password.placeholder': '请输入您的访问密码',
    'auth.form.email.label': '通讯频率链路',
    'auth.form.email.placeholder': 'example@mail.com',
    'auth.form.agree': '我已阅读并同意平台《系统协议》',
    'auth.form.recovery': '需要找回凭据？',
    'auth.form.new_node': '新节点？',
    'auth.form.init_reg': '初始化注册',
    'auth.form.has_node': '已有节点？',
    'auth.form.init_login': '执行登录指令',
    'auth.form.code.label': '验证码',
    'auth.form.confirmPassword.label': '确认密码',
    'auth.status.guest': '访客访问模式',
    'auth.status.granted': '授权通过',
    'auth.status.granted_desc': '欢迎回来，特工 {user}。会话已建立。',
    // Auth Stories
    'auth.story.1.title': '稳定胜过复杂',
    'auth.story.1.desc': '红石线每传 15 格会衰减。把中继器放在关键节点后，机器从“偶尔能跑”变成“挂机一晚都稳”。这也是大神说的：先做稳定，再做复杂。',
    'auth.story.2.title': '行为皆可预测',
    'auth.story.2.desc': '许多人第一次做交易大厅会被“串岗”折磨。老玩家总结出铁律：先封闭路径，再摆工位，最后才刷交易。',
    'auth.story.3.title': '1:8 的空间共鸣',
    'auth.story.3.desc': '下界移动 1 格等于主世界 8 格。当你推开传送门的紫色涟漪，远方同伴的火把就在路网尽头闪烁。地理没变，连接方式变了。',
    'auth.story.4.title': '超越地址的艺术',
    'auth.story.4.desc': '一个好的服务器是一件艺术品。从 MOTD 的第一行字，到主城的每一块圆石，都在向玩家宣告：这里是一个值得停留的家园。',
    'auth.story.5.title': '连接每一个灵魂',
    'auth.story.5.desc': '服联不生产服务器，我们连接它们。在这里，你不仅是管理员，更是这个庞大数字世界的共建者。',
    // Admin Dashboard
    'admin.dash.title': '全局态势感知',
    'admin.dash.subtitle': '监控全站数据与实时运行状态。执行全局安全扫描、负载预测及用户交互链路分析。',
    'admin.dash.metrics.users': '已注册实体',
    'admin.dash.metrics.servers': '活跃集群',
    'admin.dash.metrics.review': '待处理协议',
    'admin.dash.metrics.tickets': '活动工单',
    'admin.dash.flux': '实时通量',
    'admin.dash.uptime': '在线评分',
    'admin.dash.telemetry': '实时遥测数据包',
    'admin.dash.inspect_logs': '审查所有审计日志',
    'admin.dash.security_snap': '安全快照',
    'admin.dash.firewall': '防火墙完整性',
    'admin.dash.encryption': '认证加密协议',
    'admin.dash.threat': '威胁等级',
    'admin.dash.run_scan': '执行系统扫描',
    'admin.dash.maintenance': '维护纪元',
    'admin.dash.sync_msg': '全球同步预计于 {time} 后开始',
    'admin.dash.sync_desc': '下次计划维护将同步所有节点并轮换加密会话密钥。',
    'dash.activity.title': '近期活动日志 / ACTIVITY_LOGS',
    'dash.activity.sync': '身份矩阵同步成功',
    'dash.activity.handshake': '与节点 #001 建立安全握手',
    'dash.activity.firewall': '防火墙状态: 所有节点安全',

    // User Dashboard
    'dash.menu.overview': '控制台概览',
    'dash.menu.servers': '我的服务器',
    'dash.menu.tickets': '工单系统',
    'dash.menu.billing': '财务管理',
    'dash.menu.profile': '账号设置',
    'dash.logout': '退出登录',
    'dash.level_progress': '等级进度',
    'dash.financial_status': '财务状态',
    'dash.services_shortcuts': '服务与快捷方式',
    'dash.xp.remaining': '距离下一级还需要 {xp} XP',
    'dash.checkin.claimed': '今日已签到',
    'dash.checkin.now': '立即签到',
    'dash.checkin.xp_reward': '獲得 25 XP 經驗獎勵！',
    'dash.financial.billing': '财务账单记录',
    'dash.financial.desc': '管理您的余额、积分与充值记录 / FINANCIAL_CONTROL',
    'dash.financial.balance_label': '账户余额 / CREDIT_BALANCE',
    'dash.financial.recharge_btn': '立即充值 / INITIALIZE_TOPUP',
    'dash.financial.checkin_label': '每日签到 / DAILY_HANDSHAKE',
    'dash.financial.checkin_desc': '连续签到可获得额外倍率',
    'dash.financial.checkin_btn': '领取今日奖励 / CLAIM_REWARD',
    'dash.financial.checkin_loading': '正在领取...',
    'dash.financial.history_title': '最近交易记录 / RECENT_TELEMETRY',
    'dash.financial.history_type': '余额充值 / FUND_INJECT',
    // Public Server List
    'discovery.title': '探索节点.',
    'discovery.status': '目前共有 {count} 个在线服务器正在实时宣传。全网节点同步状态：正常。',
    'discovery.protocol': '全球协议已激活',
    'discovery.search.placeholder': '身份 ID / 关键字 / 协议...',
    'discovery.load_more': '加载更多节点数据',
    'discovery.buffer': '节点缓冲区: 最佳',
    'discovery.nodes_online': '实体在线',
    'discovery.status_live': '实时网络节点',
    'discovery.cat.all': '全服节点',
    'discovery.cat.survival': '生存',
    'discovery.cat.creative': '创造',
    'discovery.cat.hardcore': '极限',
    'discovery.cat.minigames': '小游戏',
    'discovery.cat.roleplay': '角色扮演',
    'dash.shortcuts.publish': '发布服务器',
    'dash.shortcuts.ticket': '发起工单',
    'dash.shortcuts.ads': '选购推广',
    // My Servers
    'dash.servers.title': '我的服务器',
    'dash.servers.broadcast': '发布新服务器',
    'dash.servers.status.approved': '已发布',
    'dash.servers.status.pending': '审核中',
    'dash.servers.status.rejected': '已驳回',
    // Server Editor
    'editor.title.new': 'BROADCAST.',
    'editor.title.edit': 'CONFIGURE.',
    'editor.subtitle': '展示您的独特世界。提交后，您的服务器将呈现在成千上万名活跃玩家面前。',
    'editor.step.init': 'Step 01: Initializing Identity',
    'editor.step.edit': 'Editing Node: {id}',
    'editor.field.name.label': '服务器名称',
    'editor.field.name.placeholder': '例如: 星辰原野 / Node_Alpha',
    'editor.field.version.label': '客户端版本',
    'editor.field.version.placeholder': '例如: 1.20.1 / Core_v1.0',
    'editor.field.ip.label': '连接地址',
    'editor.field.ip.placeholder': '例如: mc.matrix.local',
    'editor.field.tags.label': '分类标签',
    'editor.field.tags.placeholder': '例如: 生存 战争 纯净 / Survival Combat Vanilla',
    'editor.field.desc.label': '详细介绍 / DATA_STREAM_CONTENT',
    'editor.field.desc.placeholder': '详细介绍您的服务器玩法、规则、社区特色...',
    'editor.hero.label': '宣传图封面 / Hero_Matrix',
    'editor.hero.hint': 'Recommended Ratio: 16:9 / Max 5MB',
    'editor.hero.upload': 'Initialize Hero Upload',
    'editor.hero.current': 'Current_Stream_Preview',
    'editor.hero.change': '更换图片 / RELOAD_DATA',
    'editor.notice.title': '审核流程须知 / AUDIT_NOTICE',
    'editor.notice.desc': '提交后将进入人工审核流程，通常在 24 小时内完成。审核期间请确保服务器 IP 保持在线状态。',
    'editor.submit.new': 'BROADCAST_NEW_NODE',
    'editor.submit.edit': 'UPDATE_NODE_IDENTITY',
    // Rich Text Editor Toolbar
    'editor.toolbar.bold': '加粗',
    'editor.toolbar.italic': '斜体',
    'editor.toolbar.underline': '下划线',
    'editor.toolbar.strike': '删除线',
    'editor.toolbar.link': '链接',
    'editor.toolbar.image': '插入图片',
    'editor.toolbar.h1': '一级标题',
    'editor.toolbar.h2': '二级标题',
    'editor.toolbar.bullet': '无序列表',
    'editor.toolbar.ordered': '有序列表',
    'editor.toolbar.align.left': '左对齐',
    'editor.toolbar.align.center': '居中对齐',
    'editor.toolbar.align.right': '右对齐',
    'editor.toolbar.code': '代码块',
    'editor.toolbar.table': '插入表格',
    'editor.toolbar.color': '文字颜色',
    'editor.toolbar.clear': '清除格式',
    'editor.toolbar.stats.chars': '字符数',
    'editor.toolbar.stats.words': '字数',


    // Support Tickets
    'ticket.create.title': '提交工单',
    'ticket.create.subtitle': '请详细描述您遇到的问题，我们会竭诚为您解决。',
    'ticket.form.subject': '工单标题',
    'ticket.form.subject.placeholder': '简明扼要地描述您的问题',
    'ticket.form.type': '工单分类',
    'ticket.form.type.general': '一般咨询',
    'ticket.form.type.billing': '账务与充值',
    'ticket.form.type.technical': '技术故障',
    'ticket.form.type.report': '违规举报',
    'ticket.form.content': '详细内容',
    'ticket.form.content.placeholder': '请输入您问题的详细细节、截图链接或其他补充信息...',
    'ticket.status.submitted': '提交成功',
    'ticket.status.submitted_desc': '技术支持团队将尽快回复您的工单',
    'ticket.footer.hint': '在提交前，请确保您已阅读过帮助文档。我们的平均回复时间为 4 小时。',
    'ticket.back': '返回工单列表',
    'ticket.list.title': '我的工单',
    'ticket.list.desc': '提交您在使用过程中遇到的任何问题',
    'ticket.list.create': '提交新工单',
    'ticket.list.updated': '最近更新时间',
    // Profile Identity
    'profile.edit.title': 'Identity_Parameter_Sync',
    'profile.edit.avatar.label': 'Identity_Manifest_Icon',
    'profile.edit.avatar.hint': 'Neural_Link Recommended: 400x400 (PNG/JPG)',
    'profile.edit.avatar.change': 'Recalibrate Icon',
    'profile.edit.basic.title': '核心标识 / CORE_IDENTIFIERS',
    'profile.edit.basic.username': 'Identity_Handle',
    'profile.edit.basic.email': 'Data_Relay_Node',
    'profile.edit.security.title': '加密协议 / SECURITY_CIPHERS',
    'profile.edit.security.current': 'Current_Access_Key',
    'profile.edit.security.new': 'New_Cipher_Generation',
    'profile.edit.security.confirm': 'Validate_New_Cipher',
    'profile.edit.submit.basic': 'Synchronize_Identity',
    'profile.edit.submit.security': 'Update_Security_Ciphers',
    // Password Reset
    'auth.reset.title': '设置新密码',
    'auth.reset.subtitle': '请为您的账号设置一个强密码。',
    'auth.reset.new_pwd': '新密码',
    'auth.reset.confirm_pwd': '确认新密码',
    'auth.reset.submit': '重置密码',
    'auth.reset.success': '密码已重置',
    'auth.reset.success_desc': '您现在可以使用新密码登录',
    'auth.reset.invalid': '无效的请求',
    'auth.reset.missing_token': '缺少重置令牌',
    // Payment
    'payment.fail.title': '支付未成功',
    'payment.fail.desc': '订单处理过程中遇到了问题。这可能是由于支付环境异常、超时或余额不足导致的。请放心，您并没有被扣费。',
    'payment.fail.retry': '重新尝试支付',
    'payment.fail.support': '反馈支付问题',
    'payment.fail.back': '返回上一步',
    // Profile
    'profile.role.admin': '系统管理员',
    'profile.role.user': '标准节点',
    'profile.checkin': '每日握手',
    'profile.wallet.title': '信用储备',
    'profile.wallet.desc': '用于协议推广的资源分配',
    'profile.wallet.fund': '初始化资金',
    'profile.order.title': '订单拓扑',
    'profile.order.desc': '审查历史交易分类账与节点分配。',
    'profile.support.title': '技术矩阵',
    'profile.support.desc': '访问加密的支持网格以获取节点协助。',
    'profile.activity.title': '时间遥测',
    'profile.checkin.success': '握手成功，积分已发送',
    // Email Verify
    'auth.verify.title': '验证您的邮箱',
    'auth.verify.desc': '请输入发送至您注册邮箱的 6 位验证码以解锁受限功能。',
    'auth.verify.submit': '立即验证并解锁',
    'auth.verify.resend': '重新发送验证码',
    'auth.verify.sending': '正在发送中...',
    'auth.verify.success': '验证成功',
    'auth.verify.success_desc': '所有受限功能已为您解锁!',
    'auth.verify.sent': '验证码已发送',
    'auth.verify.sent_desc': '请检查您的收件箱',
    // Home extras
    'home.stats.nodes': '在线节点',
    'home.stats.latency': '同步延迟',
    'home.stats.response': '响应时间',
    'home.stats.availability': '可用性',
    'home.status.connected': '已连接',
    'home.status.sync': '同步中',
    'home.protocol': '协议: Liandeng_v4.0_Core',
    'home.learn_more': '了解更多',
    // Public Profile
    'profile.public.joined': '加入于',
    'profile.public.likes': '获得获赞',
    'profile.public.servers': '发布的服务器',
    'profile.public.view_detail': '查看详情',
    'profile.public.mysterious': '这位用户很神秘，还没有写下自我介绍。',
    // Admin Statuses
    'admin.status.enforced': '强力执行',
    'admin.status.minimal': '极低威胁',
    'admin.status.operational': '系统运行正常',
    // Common
    'common.loading': '加载中...',
    'common.success': '操作成功',
    'common.error': '操作失败',
    'common.retry': '重试',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.submit': '提交',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.settings': '设置',
    'common.page': '页码',
    'common.language': '语言',
    'common.accent': '配色',
    'common.sys_hint': '系统提示',
    'common.net_timeout': '网络超时',
    'common.net_timeout_desc': '请求处理时间过长，请稍后重试',
    // Server
    'server.join': '加入服务器',
    'server.online': '在线',
    'server.offline': '离线',
    // Auth
    'auth.email': '邮箱地址',
    'auth.password': '密码',
    'auth.username': '用户名',
    // Auth - Forgot Password
    'auth.forgot.title': '忘记密码？',
    'auth.forgot.subtitle': '请输入您的邮箱地址，我们将发送验证码以重置您的密码。',
    'auth.forgot.send_code': '发送验证码',
    'auth.forgot.verify_hint': '验证码已发送至 {email}',
    'auth.forgot.resend': '重新发送',
    'auth.forgot.verify': '验证',
    'auth.forgot.reset': '重置密码',
    'auth.no_account': '还没有账号？',
    'auth.has_account': '已有账号？',
    // Server Detail (Hub)
    'detail.nav.back': '返回节点矩阵',
    'detail.nav.ref': '节点索引',
    'detail.status.active': '节点运行中',
    'detail.protocol.v': '通讯协议 v',
    'detail.side.endpoint': '网络端点',
    'detail.side.ip_label': '服务器 IP 地址',
    'detail.side.nodes_active': '当前活跃实体',
    'detail.side.affinity': '节点亲和力',
    'detail.side.intel': '节点智能',
    'detail.side.handshake': '握手完整性',
    'detail.side.optimal': '最佳',
    'detail.tabs.overview': '总览',
    'detail.tabs.community': '社区动态',
    'detail.tabs.technical': '技术规格',
    'detail.tabs.rules': '节点规则',
    'detail.tabs.online': '在线',
    'detail.overview.mission': '节点任务简报',
    'detail.overview.init_content': '正在初始化内容流...',
    'detail.overview.feat_primary': '核心特性',
    'detail.overview.feat_latency': '超低延迟矩阵',
    'detail.overview.feat_dist': '分布式架构',
    'detail.comm.auth_user': '已授权用户',
    'detail.comm.session_stable': '会话稳定',
    'detail.comm.placeholder': '为社区动态流贡献内容...',
    'detail.comm.broadcast': '执行广播',
    'detail.comm.handshake_req': '需要建立握手',
    'detail.comm.auth_req_desc': '在贡献内容前，授权节点必须先完成同步。',
    'detail.comm.init_sync': '初始化身份同步',
    'detail.comm.live_feed': '实时动态流',
    'detail.comm.sort_latest': '排序: 最新优先',
    'detail.comm.verified': '认证节点',
    'detail.comm.authority': '矩阵权限',
    'detail.comm.supporter': '支持者',
    'detail.comm.reply': '回复动态',
    'detail.comm.report': '举报节点',
    'detail.tech.latency': '延迟优化',
    'detail.tech.uptime': '节点在线率',
    'detail.tech.integrity': '矩阵完整性',
    'detail.tech.excellent': '极佳',
    'detail.tech.stable': '稳定',
    'detail.tech.secure': '安全',
    'detail.tech.log_buffer': '技术日志缓冲区',
    'detail.side.top_nodes': '顶级实体',
    'detail.side.leaderboard': '查看完整排行榜',
    'detail.side.alert': '安全警报',
    'detail.side.integrity_guaranteed': '节点完整性受保障',
    'detail.side.encrypted': '所有通讯数据包在此节点集群内均已端到端加密。',
    'detail.side.sys_ver': '系统版本',
    'detail.side.ready': '就绪',
    // Server Portal
    'portal.handshake.init': '握手初始化...',
    'portal.protocol.secure': '协议: 安全深层链接 v4.2',
    'portal.authenticating': '正在认证数据负载',
    'portal.status.granted': '授权通过',
    'portal.status.secure': '安全连接',
    'portal.field.endpoint': '端点 IP',
    'portal.field.version': '版本',
    'portal.action.join': '初始化加入',
    'portal.diag.stream': '诊断流',
    'portal.diag.mapped': '您的身份矩阵已成功映射至节点集群',
    'portal.diag.latency': '延迟优化',
    'portal.diag.load': '集群负载',
    'portal.diag.security': '安全层级',
    'portal.diag.uptime': '节点在线率',
    'portal.diag.tunnel': '隧道稳定',
    'portal.diag.terminate': '终止连接',
    'portal.status.denied': '访问拒绝。',
    'portal.status.invalid_token': '所提供的授权令牌无效或已过期。',
    'portal.action.return': '返回探索门户',
    'portal.footer.ver': '安全门户 v4.0',
  },
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.servers': 'Servers',
    'nav.resources': 'Resources',
    'nav.team': 'Team',
    'nav.rules': 'Rules',
    'nav.promotion': 'Promotions',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    // Admin sidebar
    'admin.title': 'QianFu',
    'admin.console': 'Admin Console',
    'admin.status': 'Root_Admin',
    'admin.index': 'Index',
    'admin.users': 'Directory',
    'admin.review': 'Review',
    'admin.tickets': 'Support',
    'admin.reports': 'Sanctions',
    'admin.audit': 'Ledger',
    'admin.stats': 'Insight',
    'admin.moderation': 'Guard',
    'admin.network': 'Network',
    'admin.treasury': 'Treasury',
    'admin.logout': 'Terminate Session',
    // Settings Panel
    'prefs.title': 'Preferences',
    'prefs.subtitle': 'Language & Accent Palette',
    'prefs.language': 'Select Language',
    'prefs.accent': 'Global Accent',
    'prefs.footer': 'QianFu Console v2.0',
    // Home Page
    'home.hero.title': 'Discover the Next World',
    'home.hero.subtitle': 'QianFu Liandeng is the leading platform for Minecraft server promotion. Based on fair auction protocols, we let quality content stand out in the digital matrix.',
    'home.hero.explore': 'Explore Nodes',
    'home.hero.promote': 'Initialize Promo',
    'home.feat.security.title': 'Immutable Security',
    'home.feat.security.desc': 'Powered by SuperTokens, protecting your accounts and assets. All sessions are verified end-to-end via cryptographic tokens.',
    'home.feat.auction.title': 'Dynamic Auction',
    'home.feat.auction.desc': 'Real-time bidding algorithms ensure transparent traffic distribution. Every impression is verified by network-wide consensus.',
    'home.feat.support.title': 'Executive Support',
    'home.feat.support.desc': '24/7 ticket system with professional response teams. Sub-millisecond latency ensures your operations never halt.',
    // Auth Page
    'auth.login.title': 'Identify',
    'auth.login.subtitle': 'Please enter your access credentials to synchronize global matrix data. Executing security handshake.',
    'auth.login.submit': 'Execute Authorization',
    'auth.register.title': 'Init Node',
    'auth.register.subtitle': 'Welcome to the largest Minecraft network matrix. Please complete the form to initialize your identity.',
    'auth.register.submit': 'Sync Register Protocol',
    'auth.form.username.label': 'Source Identity',
    'auth.form.username.placeholder': 'UID / EMAIL_ADDR',
    'auth.form.password.label': 'Pass-Phrase Matrix',
    'auth.form.password.placeholder': 'Enter access passphrase',
    'auth.form.email.label': 'Comms Frequency Link',
    'auth.form.email.placeholder': 'example@mail.com',
    'auth.form.agree': 'I agree to the System Protocols',
    'auth.form.recovery': 'Recovery Needed?',
    'auth.form.new_node': 'New Node?',
    'auth.form.init_reg': 'Initialize Register',
    'auth.form.has_node': 'Already have node?',
    'auth.form.init_login': 'Execute Login',
    'auth.status.guest': 'Guest Access Mode',
    'auth.status.granted': 'ACCESS GRANTED',
    'auth.status.granted_desc': 'Welcome back, agent {user}. Session established.',
    // Auth Stories
    'auth.story.1.title': 'STABILITY OVER COMPLEXITY.',
    'auth.story.1.desc': 'Redstone signals decay every 15 blocks. Repeater placement transforms unstable machines into reliable ones. Stabilize before scaling.',
    'auth.story.2.title': 'BEHAVIOR IS PREDICTABLE.',
    'auth.story.2.desc': 'Trading halls fail due to pathing chaos. Seal paths first, then place workstations, then spawn entities. Order dictates outcome.',
    'auth.story.3.title': '1:8 SPACE COMPRESSION.',
    'auth.story.3.desc': 'The Nether folds space. Moving 1 block there equals 8 blocks here. Geography remains; connectivity evolves.',
    'auth.story.4.title': 'MORE THAN AN ADDRESS.',
    'auth.story.4.desc': 'A good server is a work of art. From the first line of MOTD to every cobblestone in spawn, it tells players: this is a home worth staying at.',
    'auth.story.5.title': 'CONNECT EVERY SOUL.',
    'auth.story.5.desc': 'Liandeng doesn\'t create servers, we connect them. Here, you are not just an admin, but a co-builder of this massive digital world.',
    // Admin Dashboard
    'admin.dash.title': 'OmniView',
    'admin.dash.subtitle': 'Monitor global data and real-time operations. Execute scans, predict loads, and analyze interaction links.',
    'admin.dash.metrics.users': 'Registered Entities',
    'admin.dash.metrics.servers': 'Active Clusters',
    'admin.dash.metrics.review': 'Pending Protocols',
    'admin.dash.metrics.tickets': 'Active Tickets',
    'admin.dash.flux': 'Real-time Flux',
    'admin.dash.uptime': 'Uptime Score',
    'admin.dash.telemetry': 'Live Telemetry Packets',
    'admin.dash.inspect_logs': 'INSPECT ALL AUDIT LOGS',
    'admin.dash.security_snap': 'Security Snapshot',
    'admin.dash.firewall': 'Firewall Integrity',
    'admin.dash.encryption': 'Auth Encryption',
    'admin.dash.threat': 'Threat Level',
    'admin.dash.run_scan': 'RUN_SYSTEM_SCAN',
    'admin.dash.maintenance': 'Maintenance Epoch',
    'admin.dash.sync_msg': 'Global Sync in {time}',
    'admin.dash.sync_desc': 'Next scheduled maintenance will synchronize all nodes and rotate cryptographic session keys.',
    'dash.activity.title': 'Recent Activity Logs / ACTIVITY_LOGS',
    'dash.activity.sync': 'Identity Matrix Synchronization Successful',
    'dash.activity.handshake': 'Secure Handshake established with Node #001',
    'dash.activity.firewall': 'Firewall status: ALL_NODES_SECURE',

    // User Dashboard
    'dash.menu.overview': 'Overview',
    'dash.menu.servers': 'My Servers',
    'dash.menu.tickets': 'Tickets',
    'dash.menu.billing': 'Billing',
    'dash.menu.profile': 'Profile',
    'dash.logout': 'Logout',
    'dash.level_progress': 'Level Progress',
    'dash.financial_status': 'Financial Status',
    'dash.services_shortcuts': 'Services & Shortcuts',
    'dash.xp.remaining': 'Need {xp} XP for next level',
    'dash.checkin.claimed': 'Already Claimed',
    'dash.checkin.now': 'Check-in Now',
    'dash.checkin.xp_reward': 'Received 25 XP Reward!',
    'dash.financial.billing': 'Financial Ledger Logs',
    'dash.financial.desc': 'Manage your balance, points and top-up records / FINANCIAL_CONTROL',
    'dash.financial.balance_label': 'CREDIT_BALANCE',
    'dash.financial.recharge_btn': 'INITIALIZE_TOPUP',
    'dash.financial.checkin_label': 'DAILY_HANDSHAKE',
    'dash.financial.checkin_desc': 'Consecutive presence grants multipliers',
    'dash.financial.checkin_btn': 'CLAIM_REWARD',
    'dash.financial.checkin_loading': 'TRANSMITTING...',
    'dash.financial.history_title': 'RECENT_TELEMETRY',
    'dash.financial.history_type': 'FUND_INJECT',
    // Public Server List
    'discovery.title': 'Discovery.',
    'discovery.status': 'Currently {count} active nodes are broadcasting. Global sync: OPTIMAL.',
    'discovery.protocol': 'Global Protocol Active',
    'discovery.search.placeholder': 'UID / KEYWORD / PROTOCOL...',
    'discovery.load_more': 'SYNCHRONIZE NEXT SECTOR',
    'discovery.buffer': 'Buffer_Status: Optimal',
    'discovery.nodes_online': 'Nodes_Online',
    'discovery.status_live': 'LIVE_NETWORK_NODE',
    'discovery.cat.all': 'All Servers',
    'discovery.cat.survival': 'Survival',
    'discovery.cat.creative': 'Creative',
    'discovery.cat.hardcore': 'Hardcore',
    'discovery.cat.minigames': 'Mini-Games',
    'discovery.cat.roleplay': 'Roleplay',
    'dash.shortcuts.publish': 'Publish Server',
    'dash.shortcuts.ticket': 'Open Ticket',
    'dash.shortcuts.ads': 'Buy Ads',
    // My Servers
    'dash.servers.title': 'My Servers',
    'dash.servers.broadcast': 'Broadcast New',
    'dash.servers.status.approved': 'Broadcasting',
    'dash.servers.status.pending': 'Pending Validation',
    'dash.servers.status.rejected': 'Rejected',
    // Server Editor
    'editor.title.new': 'BROADCAST.',
    'editor.title.edit': 'CONFIGURE.',
    'editor.subtitle': 'Showcase your unique world. Once submitted, your server will be presented to thousands of active players.',
    'editor.step.init': 'Step 01: Initializing Identity',
    'editor.step.edit': 'Editing Node: {id}',
    'editor.field.name.label': 'Name',
    'editor.field.name.placeholder': 'Example: Star_Field / Node_Alpha',
    'editor.field.version.label': 'Client Version',
    'editor.field.version.placeholder': 'Example: 1.20.1 / Core_v1.0',
    'editor.field.ip.label': 'Connection IP',
    'editor.field.ip.placeholder': 'Example: mc.matrix.local',
    'editor.field.tags.label': 'Categorical Tags',
    'editor.field.tags.placeholder': 'Example: Survival Combat Vanilla',
    'editor.field.desc.label': 'Details / DATA_STREAM_CONTENT',
    'editor.field.desc.placeholder': 'Describe your gameplay, rules, community features...',
    'editor.hero.label': 'Hero Cover / Hero_Matrix',
    'editor.hero.hint': 'Recommended Ratio: 16:9 / Max 5MB',
    'editor.hero.upload': 'Initialize Hero Upload',
    'editor.hero.current': 'Current_Stream_Preview',
    'editor.hero.change': 'Reload Image / RELOAD_DATA',
    'editor.notice.title': 'Audit Protocols / AUDIT_NOTICE',
    'editor.notice.desc': 'Submission will enter manual review, typically completed within 24h. Please ensure server IP remains online.',
    'editor.submit.new': 'BROADCAST_NEW_NODE',
    'editor.submit.edit': 'UPDATE_NODE_IDENTITY',
    // Rich Text Editor Toolbar
    'editor.toolbar.bold': 'Bold',
    'editor.toolbar.italic': 'Italic',
    'editor.toolbar.underline': 'Underline',
    'editor.toolbar.strike': 'Strikethrough',
    'editor.toolbar.link': 'Link',
    'editor.toolbar.image': 'Insert Image',
    'editor.toolbar.h1': 'Heading 1',
    'editor.toolbar.h2': 'Heading 2',
    'editor.toolbar.bullet': 'Bullet List',
    'editor.toolbar.ordered': 'Ordered List',
    'editor.toolbar.align.left': 'Align Left',
    'editor.toolbar.align.center': 'Align Center',
    'editor.toolbar.align.right': 'Align Right',
    'editor.toolbar.code': 'Code Block',
    'editor.toolbar.table': 'Insert Table',
    'editor.toolbar.color': 'Text Color',
    'editor.toolbar.clear': 'Clear Format',
    'editor.toolbar.stats.chars': 'Characters',
    'editor.toolbar.stats.words': 'Words',


    // Support Tickets
    'ticket.create.title': 'Create Ticket',
    'ticket.create.subtitle': 'Please describe your issue in detail, and we will do our best to help you.',
    'ticket.form.subject': 'Subject',
    'ticket.form.subject.placeholder': 'Briefly describe your issue',
    'ticket.form.type': 'Category',
    'ticket.form.type.general': 'General',
    'ticket.form.type.billing': 'Billing',
    'ticket.form.type.technical': 'Technical',
    'ticket.form.type.report': 'Report',
    'ticket.form.content': 'Details',
    'ticket.form.content.placeholder': 'Please enter the details of your issue, screenshot links, or other info...',
    'ticket.status.submitted': 'Submitted Successfully',
    'ticket.status.submitted_desc': 'Our support team will respond to your ticket as soon as possible.',
    'ticket.footer.hint': 'Please ensure you have read the documentation before submitting. Average response time is 4 hours.',
    'ticket.back': 'Back to Tickets',
    'ticket.list.title': 'My Tickets',
    'ticket.list.desc': 'Submit any issues you encounter during use.',
    'ticket.list.create': 'Submit New Ticket',
    'ticket.list.updated': 'Last Updated',
    // Profile Identity
    'profile.edit.title': 'Identity_Parameter_Sync',
    'profile.edit.avatar.label': 'Identity_Manifest_Icon',
    'profile.edit.avatar.hint': 'Neural_Link Recommended: 400x400 (PNG/JPG)',
    'profile.edit.avatar.change': 'Recalibrate Icon',
    'profile.edit.basic.title': 'CORE_IDENTIFIERS',
    'profile.edit.basic.username': 'Identity_Handle',
    'profile.edit.basic.email': 'Data_Relay_Node',
    'profile.edit.security.title': 'SECURITY_CIPHERS',
    'profile.edit.security.current': 'Current_Access_Key',
    'profile.edit.security.new': 'New_Cipher_Generation',
    'profile.edit.security.confirm': 'Validate_New_Cipher',
    'profile.edit.submit.basic': 'Synchronize_Identity',
    'profile.edit.submit.security': 'Update_Security_Ciphers',

    // Password Reset
    'auth.reset.title': 'Set New Password',
    'auth.reset.subtitle': 'Please set a strong password for your account.',
    'auth.reset.new_pwd': 'New Password',
    'auth.reset.confirm_pwd': 'Confirm New Password',
    'auth.reset.submit': 'Reset Password',
    'auth.reset.success': 'Password Reset Successfully',
    'auth.reset.success_desc': 'You can now login with your new password.',
    'auth.reset.invalid': 'Invalid Request',
    'auth.reset.missing_token': 'Missing reset token',
    // Payment
    'payment.fail.title': 'Payment Failed',
    'payment.fail.desc': 'An issue occurred while processing your order. This may be due to payment environment anomalies, timeouts, or insufficient balance. Rest assured, you have not been charged.',
    'payment.fail.retry': 'Retry Payment',
    'payment.fail.support': 'Report Payment Issue',
    'payment.fail.back': 'Go Back',
    // Profile
    'profile.role.admin': 'System Administrator',
    'profile.role.user': 'Standard Node',
    'profile.checkin': 'Daily Handshake',
    'profile.wallet.title': 'Credit_Reserve',
    'profile.wallet.desc': 'Allocated for protocol promotion',
    'profile.wallet.fund': 'Initialize Funding',
    'profile.order.title': 'Order Topology',
    'profile.order.desc': 'Review your historical transaction ledger and node allocations.',
    'profile.support.title': 'Technical Matrix',
    'profile.support.desc': 'Access the encrypted support grid for node assistance.',
    'profile.activity.title': 'Temporal Telemetry',
    'profile.checkin.success': 'Handshake successful, Credits sent',
    // Email Verify
    'auth.verify.title': 'Verify Your Email',
    'auth.verify.desc': 'Please enter the 6-digit code sent to your registered email to unlock restricted features.',
    'auth.verify.submit': 'Verify & Unlock Now',
    'auth.verify.resend': 'Resend Verification Code',
    'auth.verify.sending': 'Sending...',
    'auth.verify.success': 'Verification Successful',
    'auth.verify.success_desc': 'All restricted features have been unlocked!',
    'auth.verify.sent': 'Code Sent',
    'auth.verify.sent_desc': 'Please check your inbox.',
    // Home extras
    'home.status.connected': 'Connected',
    'home.status.sync': 'Sync_100%',
    'home.protocol': 'Protocol: Liandeng_v4.0_Core',
    'home.learn_more': 'Learn More',
    // Public Profile
    'profile.public.joined': 'Joined on',
    'profile.public.likes': 'Likes Received',
    'profile.public.servers': 'Published Servers',
    'profile.public.view_detail': 'View Detail',
    'profile.public.mysterious': 'This user is mysterious and has not written a bio yet.',
    // Admin Statuses
    'admin.status.enforced': 'ENFORCED',
    'admin.status.minimal': 'MINIMAL',
    'admin.status.operational': 'Systems: OPERATIONAL',
    // Common
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.settings': 'Settings',
    'common.page': 'PAGE',
    'common.language': 'Language',
    'common.accent': 'Accent Color',
    'common.sys_hint': 'System Alert',
    'common.net_timeout': 'Network Timeout',
    'common.net_timeout_desc': 'The request took too long. Please try again later.',
    // Server
    'server.join': 'Join Server',
    'server.online': 'Online',
    'server.offline': 'Offline',
    // Auth
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.username': 'Username',
    // Auth - Forgot Password
    'auth.forgot.title': 'Forgot Password?',
    'auth.forgot.subtitle': 'Enter your email address and we will send a verification code to reset your password.',
    'auth.forgot.send_code': 'Send Code',
    'auth.forgot.verify_hint': 'Code sent to {email}',
    'auth.forgot.resend': 'Resend',
    'auth.forgot.verify': 'Verify',
    'auth.forgot.reset': 'Reset Password',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    // Server Detail (Hub)
    'detail.nav.back': 'BACK_TO_GRID',
    'detail.nav.ref': 'NODE_REF',
    'detail.status.active': 'LIVE_STATUS_ACTIVE',
    'detail.protocol.v': 'PROTOCOL_V_',
    'detail.side.endpoint': 'Network_Endpoint',
    'detail.side.ip_label': 'SERVER_IP_ADDR',
    'detail.side.nodes_active': 'Current_Active_Nodes',
    'detail.side.affinity': 'Node_Affinity',
    'detail.side.intel': 'Node_Intelligence',
    'detail.side.handshake': 'Handshake_Integrity',
    'detail.side.optimal': 'OPTIMAL',
    'detail.tabs.overview': 'Overview',
    'detail.tabs.community': 'Community_Feed',
    'detail.tabs.technical': 'Tech_Specs',
    'detail.tabs.rules': 'Node_Rules',
    'detail.tabs.online': 'ONLINE',
    'detail.overview.mission': 'The_Mission_Briefing',
    'detail.overview.init_content': 'INITIALIZING_CONTENT_STREAM...',
    'detail.overview.feat_primary': 'Primary_Feature',
    'detail.overview.feat_latency': 'Ultra-Low Latency Grid',
    'detail.overview.feat_dist': 'Distributed Architecture',
    'detail.comm.auth_user': 'Authenticated_User',
    'detail.comm.session_stable': 'SESSION_STABLE',
    'detail.comm.placeholder': 'CONTRIBUTE TO THE FEED_STREAM...',
    'detail.comm.broadcast': 'BROADCAST_COMM',
    'detail.comm.handshake_req': 'Handshake Required',
    'detail.comm.auth_req_desc': 'Authorization node must be synchronized before contribution.',
    'detail.comm.init_sync': 'INITIALIZE_IDENTITY_SYNC',
    'detail.comm.live_feed': 'LIVE_FEED_STREAM',
    'detail.comm.sort_latest': 'Sort: LATEST_FIRST',
    'detail.comm.verified': 'VERIFIED_NODE',
    'detail.comm.authority': 'Matrix Authority',
    'detail.comm.supporter': 'Supporter',
    'detail.comm.reply': 'REPL_Y_STREAM',
    'detail.comm.report': 'REPOR_T_NODE',
    'detail.tech.latency': 'Latency_Optimized',
    'detail.tech.uptime': 'Node_Uptime',
    'detail.tech.integrity': 'Grid_Integrity',
    'detail.tech.excellent': 'EXCELLENT',
    'detail.tech.stable': 'STABLE',
    'detail.tech.secure': 'SECURE',
    'detail.tech.log_buffer': 'Technical_Log_Buffer',
    'detail.side.top_nodes': 'Top_Nodes',
    'detail.side.leaderboard': 'View_Full_Leaderboard',
    'detail.side.alert': 'Security_Alert',
    'detail.side.integrity_guaranteed': 'Node Integrity Guaranteed',
    'detail.side.encrypted': 'All communication packets are end-to-end encrypted within this node cluster.',
    'detail.side.sys_ver': 'SYSTEM_VER',
    'detail.side.ready': 'READY',
    // Server Portal
    'portal.handshake.init': 'Handshake_Init...',
    'portal.protocol.secure': 'Protocol: Secure_Deep_Link_v4.2',
    'portal.authenticating': 'Authenticating_Payload',
    'portal.status.granted': 'ACCESS_GRANTED',
    'portal.status.secure': 'Secure Connection',
    'portal.field.endpoint': 'ENDPOINT_IP',
    'portal.field.version': 'VERSION',
    'portal.action.join': 'Initialize Join',
    'portal.diag.stream': 'Diagnostic_Stream',
    'portal.diag.mapped': 'Your identity matrix has been successfully mapped to Node Cluster',
    'portal.diag.latency': 'Latency_Optimized',
    'portal.diag.load': 'Cluster_Load',
    'portal.diag.security': 'Security_Layer',
    'portal.diag.uptime': 'Node_Uptime',
    'portal.diag.tunnel': 'Tunnel_Stable',
    'portal.diag.terminate': 'Terminate Connection',
    'portal.status.denied': 'Access_Denied.',
    'portal.status.invalid_token': 'The provided authorization token is invalid or has expired.',
    'portal.action.return': 'Return to Discovery',
    'portal.footer.ver': 'Secure_Portal_v4.0',
  },
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.zh;
export const DEFAULT_TRANSLATIONS = TRANSLATIONS.zh;

// --- Appearance Themes ---
export type AccentTheme = 'zinc' | 'amber' | 'emerald' | 'sky' | 'violet' | 'rose';

export const accentThemes: Record<AccentTheme, {
  name: string;
  nameZh: string;
  primary: string;
  dataAttr: string;
}> = {
  zinc:    { name: 'Obsidian', nameZh: '黑曜石', primary: '#18181b', dataAttr: 'zinc'    },
  amber:   { name: 'Lantern',  nameZh: '灯笼橙', primary: '#d97706', dataAttr: 'amber'   },
  emerald: { name: 'Forest',   nameZh: '森林绿', primary: '#059669', dataAttr: 'emerald' },
  sky:     { name: 'Diamond',  nameZh: '钻石蓝', primary: '#0284c7', dataAttr: 'sky'     },
  violet:  { name: 'Chorus',   nameZh: '紫颂花', primary: '#7c3aed', dataAttr: 'violet'  },
  rose:    { name: 'Nether',   nameZh: '地狱红', primary: '#e11d48', dataAttr: 'rose'    },
};

/** 
 * applyAccent - Injects theme attribute into the document root
 */
export function applyAccent(accent: AccentTheme) {
  if (typeof document !== 'undefined') {
    document.documentElement.setAttribute('data-accent', accent);
  }
}

// --- Store Implementation ---
interface UIState {
  locale: Locale;
  accent: AccentTheme;
  setLocale: (locale: Locale) => void;
  setAccent: (accent: AccentTheme) => void;
}

export const useUIStore = create<UIState>()(
  persist(
    (set) => ({
      locale: 'zh',
      accent: 'zinc',
      setLocale: (locale) => set({ locale }),
      setAccent: (accent) => {
        set({ accent });
        applyAccent(accent);
      },
    }),
    { name: 'qianfu-ui-prefs' }
  )
);

/**
 * useT - Simple translation hook
 */
export function useT() {
  const currentLocale = useUIStore((s) => s.locale);
  
  return useCallback(
    (key: TranslationKey): string => {
      // @ts-ignore - dynamic key access
      return TRANSLATIONS[currentLocale][key] || key;
    },
    [currentLocale]
  );
}

/**
 * staticT - Translation helper for non-React contexts
 */
export function staticT(key: TranslationKey): string {
  const state = useUIStore.getState();
  const locale = state.locale || 'zh';
  // @ts-ignore
  return TRANSLATIONS[locale][key] || key;
}
