export const CHECKIN_ERROR_CODES = {
    AUTH_REQUIRED: 'CHECKIN_AUTH_REQUIRED',
    TZ_INVALID: 'CHECKIN_TZ_INVALID',
    ALREADY_DONE: 'CHECKIN_ALREADY_DONE',
    RATE_LIMITED: 'CHECKIN_RATE_LIMITED',
};
//# sourceMappingURL=checkin-codes.js.map