import { Prisma } from '../../../prisma/generated/local-client';
export declare const createServer: (data: Prisma.ServerCreateInput) => Promise<{
    link: string | null;
    review_notes: string | null;
    ip: string | null;
    name: string;
    id: number;
    created_at: Date;
    updated_at: Date;
    activity: number;
    owner_id: number;
    reviewed_by: number | null;
    like_count: number;
    comment_count: number;
    supported_versions: string | null;
    network_env: string | null;
    name_en: string | null;
    thumbnail: string | null;
    summary: string | null;
    summary_en: string | null;
    content_html: string | null;
    group_number: string | null;
    tags: string | null;
    platform: string | null;
    category: string | null;
    online_mode: boolean | null;
    synced_at: Date | null;
    review_status: string;
    reviewed_at: Date | null;
}>;
export declare const getServerById: (id: number) => Promise<{
    link: string | null;
    review_notes: string | null;
    ip: string | null;
    name: string;
    id: number;
    created_at: Date;
    updated_at: Date;
    activity: number;
    owner_id: number;
    reviewed_by: number | null;
    like_count: number;
    comment_count: number;
    supported_versions: string | null;
    network_env: string | null;
    name_en: string | null;
    thumbnail: string | null;
    summary: string | null;
    summary_en: string | null;
    content_html: string | null;
    group_number: string | null;
    tags: string | null;
    platform: string | null;
    category: string | null;
    online_mode: boolean | null;
    synced_at: Date | null;
    review_status: string;
    reviewed_at: Date | null;
} | null>;
export declare const getAllServers: () => Promise<{
    link: string | null;
    review_notes: string | null;
    ip: string | null;
    name: string;
    id: number;
    created_at: Date;
    updated_at: Date;
    activity: number;
    owner_id: number;
    reviewed_by: number | null;
    like_count: number;
    comment_count: number;
    supported_versions: string | null;
    network_env: string | null;
    name_en: string | null;
    thumbnail: string | null;
    summary: string | null;
    summary_en: string | null;
    content_html: string | null;
    group_number: string | null;
    tags: string | null;
    platform: string | null;
    category: string | null;
    online_mode: boolean | null;
    synced_at: Date | null;
    review_status: string;
    reviewed_at: Date | null;
}[]>;
export declare const updateServer: (id: number, data: Prisma.ServerUpdateInput) => Promise<{
    link: string | null;
    review_notes: string | null;
    ip: string | null;
    name: string;
    id: number;
    created_at: Date;
    updated_at: Date;
    activity: number;
    owner_id: number;
    reviewed_by: number | null;
    like_count: number;
    comment_count: number;
    supported_versions: string | null;
    network_env: string | null;
    name_en: string | null;
    thumbnail: string | null;
    summary: string | null;
    summary_en: string | null;
    content_html: string | null;
    group_number: string | null;
    tags: string | null;
    platform: string | null;
    category: string | null;
    online_mode: boolean | null;
    synced_at: Date | null;
    review_status: string;
    reviewed_at: Date | null;
}>;
export declare const deleteServer: (id: number) => Promise<{
    link: string | null;
    review_notes: string | null;
    ip: string | null;
    name: string;
    id: number;
    created_at: Date;
    updated_at: Date;
    activity: number;
    owner_id: number;
    reviewed_by: number | null;
    like_count: number;
    comment_count: number;
    supported_versions: string | null;
    network_env: string | null;
    name_en: string | null;
    thumbnail: string | null;
    summary: string | null;
    summary_en: string | null;
    content_html: string | null;
    group_number: string | null;
    tags: string | null;
    platform: string | null;
    category: string | null;
    online_mode: boolean | null;
    synced_at: Date | null;
    review_status: string;
    reviewed_at: Date | null;
}>;
//# sourceMappingURL=serverService.d.ts.map