import { Prisma } from '../../../prisma/generated/local-client';
export declare const createServerStatus: (data: Prisma.ServerStatusCreateInput) => Promise<{
    id: number;
    port: number;
    host: string;
    serverId: number;
    online: boolean;
    createdAt: Date;
    playersOnline: number | null;
    versionNameRaw: string | null;
    versionProtocol: number | null;
    playersMax: number | null;
    playersList: string | null;
    motdRaw: string | null;
    motdClean: string | null;
    motdHtml: string | null;
    favicon: string | null;
    srvRecord: string | null;
    lastUpdated: Date;
}>;
export declare const getServerStatusById: (id: number) => Promise<{
    id: number;
    port: number;
    host: string;
    serverId: number;
    online: boolean;
    createdAt: Date;
    playersOnline: number | null;
    versionNameRaw: string | null;
    versionProtocol: number | null;
    playersMax: number | null;
    playersList: string | null;
    motdRaw: string | null;
    motdClean: string | null;
    motdHtml: string | null;
    favicon: string | null;
    srvRecord: string | null;
    lastUpdated: Date;
} | null>;
export declare const getServerStatusByServerId: (serverId: number) => Promise<{
    id: number;
    port: number;
    host: string;
    serverId: number;
    online: boolean;
    createdAt: Date;
    playersOnline: number | null;
    versionNameRaw: string | null;
    versionProtocol: number | null;
    playersMax: number | null;
    playersList: string | null;
    motdRaw: string | null;
    motdClean: string | null;
    motdHtml: string | null;
    favicon: string | null;
    srvRecord: string | null;
    lastUpdated: Date;
} | null>;
export declare const updateServerStatus: (id: number, data: Prisma.ServerStatusUpdateInput) => Promise<{
    id: number;
    port: number;
    host: string;
    serverId: number;
    online: boolean;
    createdAt: Date;
    playersOnline: number | null;
    versionNameRaw: string | null;
    versionProtocol: number | null;
    playersMax: number | null;
    playersList: string | null;
    motdRaw: string | null;
    motdClean: string | null;
    motdHtml: string | null;
    favicon: string | null;
    srvRecord: string | null;
    lastUpdated: Date;
}>;
export declare const deleteServerStatus: (id: number) => Promise<{
    id: number;
    port: number;
    host: string;
    serverId: number;
    online: boolean;
    createdAt: Date;
    playersOnline: number | null;
    versionNameRaw: string | null;
    versionProtocol: number | null;
    playersMax: number | null;
    playersList: string | null;
    motdRaw: string | null;
    motdClean: string | null;
    motdHtml: string | null;
    favicon: string | null;
    srvRecord: string | null;
    lastUpdated: Date;
}>;
//# sourceMappingURL=serverStatusService.d.ts.map