CREATE TABLE IF NOT EXISTS "UserExperienceEvent" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "event_key" TEXT NOT NULL,
  "source_id" INTEGER NOT NULL,
  "amount" INTEGER NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "UserExperienceEvent_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "UserExperienceEvent_user_id_event_key_source_id_key"
  ON "UserExperienceEvent" ("user_id", "event_key", "source_id");

CREATE INDEX IF NOT EXISTS "UserExperienceEvent_user_id_created_at_idx"
  ON "UserExperienceEvent" ("user_id", "created_at");
